FUNCTION-POOL ZFG_BDS   MESSAGE-ID TD.

INCLUDE ZIN_COMMONTOP.

TYPE-POOLS: CNDP.

"MESSAGE-ID ..

* INCLUDE LZFG_BDSD...                       " Local class definition
TABLES: SDOKSTCA, SDOKPHCL, SDOKCLPROP, SDOKPROP, BDS_LOCL, CREP.

TABLES:
  ZST_BDS_UPIMG.


DATA:
  GW_REFRESH_PIC    TYPE XMARK,
  GO_CONTAINER_NEW  TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
  GO_CONTAINER_OLD  TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
  GO_PIC_NEW        TYPE REF TO CL_GUI_PICTURE,
  GO_PIC_OLD        TYPE REF TO CL_GUI_PICTURE.
