FUNCTION ZFM_ALV_EXCL_EDIT_FC.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  EXPORTING
*"     REFERENCE(T_EXCL_FC) TYPE  UI_FUNCTIONS
*"--------------------------------------------------------------------
DATA:
     LS_FUNCTION  TYPE UI_FUNC.

  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FG_EDIT.
  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_LOC_CUT.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_LOC_PASTE_NEW_ROW.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_LOC_UNDO.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_LOC_INSERT_ROW.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_LOC_DELETE_ROW.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_LOC_COPY_ROW.
*  APPEND LS_FUNCTION TO T_EXCL_FC.

  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_REFRESH.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_CHECK.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_GRAPH.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_INFO.
  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_SUM.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_SUBTOT.
*  APPEND LS_FUNCTION TO T_EXCL_FC.

  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_PRINT.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_VIEWS.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_VIEW_CRYSTAL.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_VIEW_GRID.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_VIEW_LOTUS.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_WORD_PROCESSOR.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_CALL_ABC.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_PC_FILE.
  APPEND LS_FUNCTION TO T_EXCL_FC.
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_PRINT_PREV.
  APPEND LS_FUNCTION TO T_EXCL_FC.

*----------------------------------------------------*
  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_FC_VIEW_EXCEL.
  APPEND LS_FUNCTION TO T_EXCL_FC.
*----------------------------------------------------*

*----------------------------------------------------*
*giangnt25 start del
* -> cho phep xuat du lieu ra dinh dang cho phep
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_MB_EXPORT.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*giangnt25 end del
*----------------------------------------------------*

*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_MB_FILTER.
*  APPEND LS_FUNCTION TO T_EXCL_FC.
*  LS_FUNCTION = CL_GUI_ALV_GRID=>MC_MB_PASTE.
*  APPEND LS_FUNCTION TO T_EXCL_FC.





ENDFUNCTION.
