FUNCTION ZFM_DATA_MOVE_STR.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_SRC_STR) TYPE  ANY
*"     REFERENCE(I_TRANS_FIELDS) TYPE  ANY
*"     REFERENCE(I_STRUCTURE) TYPE  TABNAME
*"  EXPORTING
*"     REFERENCE(E_DES_STR) TYPE  ANY
*"  EXCEPTIONS
*"      NO_STRUCTURE
*"--------------------------------------------------------------------
DATA:
    LT_FIELDCAT       TYPE LVC_T_FCAT,
    LS_FIELDCAT       TYPE LVC_S_FCAT.
  FIELD-SYMBOLS:
    <LF_FIELD_TRANS>  TYPE ANY,
    <LF_FIELD_SRC>    TYPE ANY,
    <LF_FIELD_DES>    TYPE ANY.

  IF I_STRUCTURE IS INITIAL.
    RAISE NO_STRUCTURE.
  ENDIF.

* Get table name and field category
  CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
    EXPORTING
      I_STRUCTURE_NAME       = I_STRUCTURE
      I_INTERNAL_TABNAME     = I_STRUCTURE
    CHANGING
      CT_FIELDCAT            = LT_FIELDCAT
    EXCEPTIONS
      INCONSISTENT_INTERFACE = 1
      PROGRAM_ERROR          = 2
      OTHERS                 = 3.

* Move data from each field was marked 'Transport'
  LOOP AT LT_FIELDCAT INTO LS_FIELDCAT.
    UNASSIGN: <LF_FIELD_SRC>,
              <LF_FIELD_DES>.
    ASSIGN COMPONENT LS_FIELDCAT-FIELDNAME OF STRUCTURE I_SRC_STR
      TO <LF_FIELD_SRC>.
    ASSIGN COMPONENT LS_FIELDCAT-FIELDNAME OF STRUCTURE E_DES_STR
      TO <LF_FIELD_DES>.
    ASSIGN COMPONENT LS_FIELDCAT-FIELDNAME OF STRUCTURE I_TRANS_FIELDS
      TO <LF_FIELD_TRANS>.
    IF <LF_FIELD_SRC> IS ASSIGNED AND <LF_FIELD_DES> IS ASSIGNED
    AND <LF_FIELD_TRANS> IS ASSIGNED AND <LF_FIELD_TRANS> = GC_XMARK.
      <LF_FIELD_DES> = <LF_FIELD_SRC>.
    ENDIF.
  ENDLOOP.





ENDFUNCTION.
