FUNCTION ZFM_BM_DF_FCHK_GRP_PUT .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_FIELD)
*"     REFERENCE(I_DF_FIELD) TYPE  ZST_BM_DF_FIELD
*"     REFERENCE(I_FIELDCODE)
*"----------------------------------------------------------------------
  DATA:
    LS_DF_CHKGRP_DAT          TYPE ZST_BM_DF_CHKGRP_DAT.

  IF I_DF_FIELD-CHKGRP IS NOT INITIAL.
    LS_DF_CHKGRP_DAT-TABNM  = I_DF_FIELD-TABNM.
    LS_DF_CHKGRP_DAT-CHKGRP = I_DF_FIELD-CHKGRP.
    PERFORM 9999_SPLIT_GET_SINGLE_FIELD
      USING I_DF_FIELD-FNAME
      CHANGING LS_DF_CHKGRP_DAT-FNAME.
    LS_DF_CHKGRP_DAT-FCODE  = I_FIELDCODE.
    GET REFERENCE OF I_FIELD INTO LS_DF_CHKGRP_DAT-VALUE.
    APPEND LS_DF_CHKGRP_DAT TO GT_DF_CHKGRP_DAT.
  ENDIF.

ENDFUNCTION.
