FUNCTION ZFM_ALV_DISPLAY_SCR_REFRESH.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_ALV_GRID) TYPE REF TO  CL_GUI_ALV_GRID OPTIONAL
*"     REFERENCE(I_ALV_HEADER_DOC) TYPE REF TO  CL_DD_DOCUMENT OPTIONAL
*"     REFERENCE(IT_HEADER) TYPE  ZTT_ALV_HEADER OPTIONAL
*"     REFERENCE(I_LOGO) TYPE  ZST_BM_ALV_LOGO OPTIONAL
*"     REFERENCE(I_HEIGHT) TYPE  I OPTIONAL
*"     REFERENCE(IS_LAYOUT) TYPE  LVC_S_LAYO OPTIONAL
*"     REFERENCE(IT_FIELDCAT) TYPE  LVC_T_FCAT OPTIONAL
*"----------------------------------------------------------------------
DATA:
    LO_SPLITTER               TYPE REF TO CL_GUI_SPLITTER_CONTAINER.

  IF I_ALV_GRID IS BOUND.
    IF IT_FIELDCAT IS NOT INITIAL.
      CALL METHOD I_ALV_GRID->SET_FRONTEND_FIELDCATALOG
        EXPORTING
          IT_FIELDCATALOG = IT_FIELDCAT.
    ENDIF.

    IF IS_LAYOUT IS NOT INITIAL.
      CALL METHOD I_ALV_GRID->SET_FRONTEND_LAYOUT
        EXPORTING
          IS_LAYOUT = IS_LAYOUT.
    ENDIF.

    CALL METHOD I_ALV_GRID->REFRESH_TABLE_DISPLAY.
  ENDIF.

  IF I_ALV_HEADER_DOC IS SUPPLIED
  AND I_ALV_HEADER_DOC IS BOUND.
*   Set new height
    IF I_HEIGHT IS NOT INITIAL.
      LO_SPLITTER ?= I_ALV_HEADER_DOC->HTML_CONTROL->PARENT->PARENT.
      CALL METHOD LO_SPLITTER->SET_ROW_HEIGHT
        EXPORTING
          ID     = 1
          HEIGHT = I_HEIGHT.
    ENDIF.

*   Show header document
    PERFORM 9999_SHOW_HTML_DOC
      USING I_ALV_HEADER_DOC
            IT_HEADER
            I_LOGO.
  ENDIF.





ENDFUNCTION.
