FUNCTION ZFM_FILE_EXCEL_IMP2TAB.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_LOCALFILE)
*"     REFERENCE(T_SHEET_MAPPING) TYPE  ANY TABLE OPTIONAL
*"     REFERENCE(T_EXCEL_MAPPING) TYPE  ZTT_EXCEL_MAPPING OPTIONAL
*"     REFERENCE(T_FIELDCAT) TYPE  LVC_T_FCAT
*"     REFERENCE(T_SHEET_ROWST) TYPE  ZTT_SHEET_ROWST
*"     REFERENCE(I_NEEDOPEN) TYPE  XMARK OPTIONAL
*"     REFERENCE(I_SHEETFIELD) TYPE  FIELDNAME DEFAULT 'SHEETNAME'
*"     REFERENCE(I_ROWIXFIELD) TYPE  FIELDNAME OPTIONAL
*"     REFERENCE(I_CLOSEFILE) TYPE  XMARK OPTIONAL
*"     REFERENCE(I_READING_LINE) TYPE  INT4 DEFAULT 100
*"  EXPORTING
*"     REFERENCE(T_IMPTAB) TYPE  ANY TABLE
*"  EXCEPTIONS
*"      OPENFILE_ERROR
*"      NO_MAPPING
*"      READ_DATA_ERROR
*"      MAPPING_ERROR
*"--------------------------------------------------------------------
DATA:
    LT_SHEETDATA            TYPE GTY_T_SHEETDATA,
    LS_SHEETDATA            TYPE GTY_SHEETDATA,
    LT_EXCEL_MAPPING_ALL    TYPE ZTT_EXCEL_MAPPING,
    LT_EXCEL_MAPPING        TYPE ZTT_EXCEL_MAPPING,
    LW_ERROR                TYPE XMARK,
    LW_FILENAME             TYPE LOCALFILE.

  IF I_NEEDOPEN IS NOT INITIAL.
    LW_FILENAME = I_LOCALFILE.
    CALL FUNCTION 'ZFM_DOI_EXCEL_OPEN'
      EXPORTING
        I_FILENAME     = LW_FILENAME
        I_READ_ONLY    = 'X'
      EXCEPTIONS
        OPEN_FILE_ERR  = 1
        OPEN_SHEET_ERR = 2
        OTHERS         = 3.
    IF SY-SUBRC <> 0.
      RAISE OPENFILE_ERROR.
    ENDIF.
  ENDIF.

  IF  T_EXCEL_MAPPING[] IS INITIAL
  AND T_SHEET_MAPPING[] IS INITIAL.
    RAISE NO_MAPPING.
  ENDIF.

  IF T_SHEET_MAPPING IS NOT INITIAL.
    CALL FUNCTION 'ZFM_FILE_EXCEL_CONV_MAPPING'
      EXPORTING
        T_SHEET_MAPPING = T_SHEET_MAPPING
        I_SHEETFIELD    = I_SHEETFIELD
      IMPORTING
        T_EXCEL_MAPPING = LT_EXCEL_MAPPING_ALL
      EXCEPTIONS
        NO_MAPPING      = 1
        NO_SHEETNAME    = 2
        OTHERS          = 3.
    IF SY-SUBRC <> 0.
      RAISE MAPPING_ERROR.
    ENDIF.
  ELSE.
    LT_EXCEL_MAPPING_ALL = T_EXCEL_MAPPING.
  ENDIF.

* Get data
  CLEAR: LT_SHEETDATA[].
  PERFORM GET_EXCEL_FILE_DATA
    USING     T_SHEET_ROWST
              LT_EXCEL_MAPPING_ALL
              I_READING_LINE
    CHANGING  LT_SHEETDATA.


* Convert data to table
  LOOP AT LT_SHEETDATA INTO LS_SHEETDATA.

    CALL FUNCTION 'ZFM_FILE_EXCEL_CONV2TAB_MAP'
      EXPORTING
        T_MAPPING    = LT_EXCEL_MAPPING_ALL
        T_EXCEL      = LS_SHEETDATA-SHEETDATA
        T_FIELDCAT   = T_FIELDCAT
        I_SHEETFIELD = I_SHEETFIELD
        I_ROWIXFIELD = I_ROWIXFIELD
        I_SHEETNAME  = LS_SHEETDATA-SHTNM
      IMPORTING
        T_OUTTAB     = T_IMPTAB.
  ENDLOOP.

* Close file
  IF I_CLOSEFILE = 'X'.
    CALL FUNCTION 'ZFM_DOI_EXCEL_CLOSE'
      EXPORTING
        I_FILENAME  = LW_FILENAME
        I_OPEN_FILE = ''.
  ENDIF.





ENDFUNCTION.
