FUNCTION ZFM_FILE_EXCEL_CONV_EXDAT2TAB.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(T_SHEET_MAPPING) TYPE  ANY TABLE OPTIONAL
*"     REFERENCE(T_EXCEL_MAPPING) TYPE  ZTT_EXCEL_MAPPING OPTIONAL
*"     REFERENCE(T_FIELDCAT) TYPE  LVC_T_FCAT
*"     REFERENCE(I_SHEETFIELD) TYPE  FIELDNAME DEFAULT 'SHEETNAME'
*"     REFERENCE(I_ROWIXFIELD) TYPE  FIELDNAME OPTIONAL
*"     REFERENCE(T_FILEDATA) TYPE  ZTT_EXCEL_IMP OPTIONAL
*"  EXPORTING
*"     REFERENCE(T_IMPTAB) TYPE  ANY TABLE
*"  EXCEPTIONS
*"      NO_MAPPING
*"      MAPPING_ERROR
*"--------------------------------------------------------------------
DATA:
    LS_FILEDATA             TYPE ZST_EXCEL_IMP,
    LT_EXCEL_MAPPING_ALL    TYPE ZTT_EXCEL_MAPPING,
    LT_EXCEL_MAPPING        TYPE ZTT_EXCEL_MAPPING,
    LW_ERROR                TYPE XMARK.

  FIELD-SYMBOLS:
    <LF_CELL>               TYPE ZST_EXCEL.

  IF  T_EXCEL_MAPPING[] IS INITIAL
  AND T_SHEET_MAPPING[] IS INITIAL.
    RAISE NO_MAPPING.
  ENDIF.

  IF T_SHEET_MAPPING IS NOT INITIAL.
    CALL FUNCTION 'ZFM_FILE_EXCEL_CONV_MAPPING'
      EXPORTING
        T_SHEET_MAPPING = T_SHEET_MAPPING
        I_SHEETFIELD    = I_SHEETFIELD
      IMPORTING
        T_EXCEL_MAPPING = LT_EXCEL_MAPPING_ALL
      EXCEPTIONS
        NO_MAPPING      = 1
        NO_SHEETNAME    = 2
        OTHERS          = 3.
    IF SY-SUBRC <> 0.
      RAISE MAPPING_ERROR.
    ENDIF.
  ELSE.
    LT_EXCEL_MAPPING_ALL = T_EXCEL_MAPPING.
  ENDIF.

* Delete mapping null
  DELETE LT_EXCEL_MAPPING_ALL WHERE COLUMN IS INITIAL.

* Convert data to table
  LOOP AT T_FILEDATA INTO LS_FILEDATA.
*   Get mapping
    LT_EXCEL_MAPPING = LT_EXCEL_MAPPING_ALL.
    DELETE LT_EXCEL_MAPPING WHERE SHEETNAME <> LS_FILEDATA-SHEETNAME.
    CHECK LT_EXCEL_MAPPING[] IS NOT INITIAL.

*   Get range data after row start
    LOOP AT LS_FILEDATA-EXDAT ASSIGNING <LF_CELL>.
      IF <LF_CELL>-ROW < LS_FILEDATA-ROWST.
        CLEAR <LF_CELL>-ROW.
      ENDIF.
    ENDLOOP.
*   Delete data b?o row start
    DELETE LS_FILEDATA-EXDAT WHERE ROW IS INITIAL.
*   Check  data
    IF LS_FILEDATA-EXDAT IS INITIAL.
      CONTINUE.
    ENDIF.

    CALL FUNCTION 'ZFM_FILE_EXCEL_CONV2TAB_MAP'
      EXPORTING
        T_MAPPING    = LT_EXCEL_MAPPING
        T_EXCEL      = LS_FILEDATA-EXDAT
        T_FIELDCAT   = T_FIELDCAT
        I_SHEETFIELD = I_SHEETFIELD
        I_ROWIXFIELD = I_ROWIXFIELD
        I_SHEETNAME  = LS_FILEDATA-SHEETNAME
      IMPORTING
        T_OUTTAB     = T_IMPTAB.
  ENDLOOP.





ENDFUNCTION.
