FUNCTION ZFM_BM_CHART_DISPLAY_TIMER.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IT_TABDATA) TYPE  TABLE
*"     REFERENCE(I_INTERVAL) TYPE  I DEFAULT 60
*"     REFERENCE(I_SUBR_REFDATA) TYPE  SLIS_FORMNAME
*"     REFERENCE(I_ON_CALL) TYPE  XMARK OPTIONAL
*"     REFERENCE(I_CPROG) TYPE  CPROG DEFAULT SY-CPROG
*"     REFERENCE(I_DYNNR) TYPE  DYNNR DEFAULT SY-DYNNR
*"     REFERENCE(I_CUS_CONTROL_NAME) TYPE  SCRFNAME
*"         DEFAULT 'CUS_CHART'
*"     REFERENCE(I_EXTENSION) TYPE  INT4 DEFAULT 800
*"     REFERENCE(I_SIDE) TYPE  INT4 DEFAULT 1
*"--------------------------------------------------------------------
DATA:
    LO_IXML_DATA_DOC   TYPE REF TO IF_IXML_DOCUMENT,
    LO_IXML_CUSTOM_DOC TYPE REF TO IF_IXML_DOCUMENT,
    LO_OSTREAM         TYPE REF TO IF_IXML_OSTREAM,
    LW_XSTR            TYPE XSTRING,
    LW_STR             TYPE STRING.

  CALL FUNCTION 'ZFM_BM_CHART_STD_GET_CONFIG'
    EXPORTING
      I_CPROG      = I_CPROG
    CHANGING
      C_CHART_CONF = GS_BM_CHART_CONF.

* For initial display of graph data.
  IF GO_CHART_ENGINE IS INITIAL.
*   Create chart objects
    PERFORM CREATE_CHART_OBJECTS
      USING I_ON_CALL
            I_EXTENSION
            I_SIDE
            I_CUS_CONTROL_NAME
            I_CPROG I_DYNNR.

*   Set fontend layout. Default 2D bar.
    PERFORM CHART_STD_CUST_LOAD
      CHANGING GO_CHART_ENGINE.
  ENDIF.

* Create timer object
  PERFORM 9999_CHART_CREATE_OBJ_TIMER
    USING I_INTERVAL
          I_CPROG
          I_SUBR_REFDATA
          GS_BM_CHART_CONF
          IT_TABDATA.

* Bind data to chart
  PERFORM CHART_STD_BIND_DATA
    USING GS_BM_CHART_CONF
          IT_TABDATA
    CHANGING GO_CHART_ENGINE.

  IF I_ON_CALL IS INITIAL.
    CALL SCREEN 0100.
  ELSE.
*   Render the Graph Object.
    CALL METHOD GO_CHART_ENGINE->RENDER.
    CALL METHOD GO_CHART_TIMER->RUN.
  ENDIF.





ENDFUNCTION.
