FUNCTION ZFM_DOI_EXCEL_OPEN.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_FILENAME) TYPE  LOCALFILE
*"     REFERENCE(I_CONTAINER_NAME) TYPE  SCRFNAME OPTIONAL
*"     REFERENCE(I_READ_ONLY) TYPE  XMARK OPTIONAL
*"  EXPORTING
*"     REFERENCE(E_SPREADSHEET) TYPE REF TO I_OI_SPREADSHEET
*"     REFERENCE(T_SHEETS) TYPE  SOI_SHEETS_TABLE
*"  EXCEPTIONS
*"      OPEN_FILE_ERR
*"      OPEN_SHEET_ERR
*"--------------------------------------------------------------------
DATA:
    LW_DOCUMENT_URL   TYPE CHAR256,
    LO_ERROR          TYPE REF TO I_OI_ERROR,
    LW_RETCODE        TYPE SOI_RET_STRING,
    LW_I              TYPE I,
    LW_CONTAINER_NAME TYPE SCRFNAME VALUE 'CTRL_EXCEL_CONTAINER'.

* Get container name
  IF I_CONTAINER_NAME IS INITIAL.
*  IF I_CONTAINER_NAME IS NOT INITIAL.
    LW_CONTAINER_NAME = I_CONTAINER_NAME.
  ENDIF.

* Create container
  PERFORM CREATE_CONTAINER USING LW_CONTAINER_NAME.

  CONCATENATE 'FILE://' I_FILENAME INTO LW_DOCUMENT_URL.

* Open an Existing Document
  CALL METHOD GO_DOCUMENT->OPEN_DOCUMENT
    EXPORTING
      DOCUMENT_TITLE = 'Excel'
      DOCUMENT_URL   = LW_DOCUMENT_URL
*      NO_FLUSH       = 'X'
      OPEN_INPLACE   = 'X'
*      OPEN_INPLACE   = I_READ_ONLY
      ONSAVE_MACRO   = ''
      OPEN_READONLY  = I_READ_ONLY
    IMPORTING
      ERROR          = LO_ERROR.
  IF LO_ERROR->HAS_FAILED = 'X'.
    RAISE OPEN_FILE_ERR.
  ENDIF.

* Get interface
  CALL METHOD GO_DOCUMENT->GET_SPREADSHEET_INTERFACE
    EXPORTING
      NO_FLUSH        = ''
    IMPORTING
      SHEET_INTERFACE = GO_SPREADSHEET
      ERROR           = LO_ERROR.
  IF LO_ERROR->HAS_FAILED = 'X'.
    PERFORM CLOSE_DOCUMENT.
    RAISE OPEN_FILE_ERR.
  ENDIF.

* Get the Names of Worksheets
  CALL METHOD GO_SPREADSHEET->GET_SHEETS
    EXPORTING
      NO_FLUSH = ''
    IMPORTING
      SHEETS   = GT_SHEETS
      ERROR    = LO_ERROR.
  IF LO_ERROR->HAS_FAILED = 'X'.
    PERFORM CLOSE_DOCUMENT.
    RAISE OPEN_SHEET_ERR.
  ENDIF.

* Export data
  E_SPREADSHEET = GO_SPREADSHEET.
  T_SHEETS      = GT_SHEETS.





ENDFUNCTION.
