FUNCTION ZFM_DATA_UPDATE_TABLE.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_STRUCTURE) TYPE  TABNAME OPTIONAL
*"     REFERENCE(T_FIELDCAT) TYPE  LVC_T_FCAT OPTIONAL
*"     REFERENCE(T_TABLE_CHANGED) TYPE  ANY TABLE OPTIONAL
*"     REFERENCE(T_TABLE_ORIGINAL) TYPE  ANY TABLE OPTIONAL
*"     REFERENCE(I_GET_ORG_DATA) TYPE  XMARK OPTIONAL
*"     REFERENCE(I_DEL_FIELD) TYPE  FIELDNAME OPTIONAL
*"     REFERENCE(I_ASSIGN_RQ) TYPE  XMARK OPTIONAL
*"  EXPORTING
*"     REFERENCE(T_TABLE_DELETE) TYPE  ANY TABLE
*"     REFERENCE(T_TABLE_UPDATE) TYPE  ANY TABLE
*"     REFERENCE(T_TABLE_INSERT) TYPE  ANY TABLE
*"  EXCEPTIONS
*"      NO_STRUCTURE
*"      CONFLICT_STRUCTURE
*"      NO_ORIGINAL_DATA
*"      CONFLICT_ORIGINAL_DATA
*"      NO_DATA
*"      UPDATE_ERROR
*"      INSERT_ERROR
*"      DELETE_ERROR
*"      DEL_FIELD_NOT_EXISTS
*"----------------------------------------------------------------------

* Check input parameters
  PERFORM CHECK_PARAMETERS
      USING I_STRUCTURE
            T_FIELDCAT
            T_TABLE_CHANGED
            T_TABLE_ORIGINAL
            I_GET_ORG_DATA.

* Get field catelog
  PERFORM GET_FIELDCAT USING I_STRUCTURE T_FIELDCAT.

* Create table using structure
  PERFORM CREATE_TABLE_WITH_KEYS.

* Get original data in database if need
  PERFORM GET_ORG_DATA
    USING T_TABLE_CHANGED T_TABLE_ORIGINAL I_GET_ORG_DATA.

* Modify data
  PERFORM MODIFY_DATA
    USING I_DEL_FIELD
          I_ASSIGN_RQ
    CHANGING T_TABLE_DELETE
             T_TABLE_UPDATE
             T_TABLE_INSERT.

ENDFUNCTION.
