FUNCTION ZFM_SCR_COMPLEX_TOGGLE_ICON.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_HEADER_OFF) TYPE  ICON_TEXT OPTIONAL
*"     VALUE(I_DETAIL_OFF) TYPE  ICON_TEXT OPTIONAL
*"     VALUE(I_DETITM_OFF) TYPE  ICON_TEXT OPTIONAL
*"  CHANGING
*"     REFERENCE(C_SCR_DATA) OPTIONAL
*"     REFERENCE(C_SCR_COMPLEX_STS) TYPE  ZST_SCR_COMPLEX_STS OPTIONAL
*"----------------------------------------------------------------------
* if screen structure is initial, use screen data
  IF C_SCR_COMPLEX_STS IS INITIAL.
    MOVE-CORRESPONDING C_SCR_DATA TO C_SCR_COMPLEX_STS.
  ENDIF.

* Set icon for header
  PERFORM 9000_SET_TOGGLE_ICON
    USING I_HEADER_OFF
    CHANGING C_SCR_COMPLEX_STS-ICONHDR_ON
             C_SCR_COMPLEX_STS-ICONHDR_OFF.

* Set icon for item overview
  PERFORM 9000_SET_TOGGLE_ICON
    USING I_DETAIL_OFF
    CHANGING C_SCR_COMPLEX_STS-ICONDET_ON
             C_SCR_COMPLEX_STS-ICONDET_OFF.

* Set icon for item detail
  PERFORM 9000_SET_TOGGLE_ICON
    USING I_DETITM_OFF
    CHANGING C_SCR_COMPLEX_STS-ICONDTI_ON
             C_SCR_COMPLEX_STS-ICONDTI_OFF.

  IF C_SCR_DATA IS REQUESTED.
    MOVE-CORRESPONDING C_SCR_COMPLEX_STS TO C_SCR_DATA.
  ENDIF.

ENDFUNCTION.
