FUNCTION ZFM_OLE_EXCEL_PAGESETUP.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_EXCEL) TYPE  OLE2_OBJECT OPTIONAL
*"     REFERENCE(I_PAGESETUP) TYPE  ZST_EXCEL_PAGESETUP
*"--------------------------------------------------------------------
DATA:
        LS_EXCEL        TYPE OLE2_OBJECT,
        LS_EXCEL_DATA   TYPE SOI_GENERIC_ITEM,
        LS_ACTIVESHEET  TYPE OLE2_OBJECT,
        LS_PAGESET      TYPE OLE2_OBJECT.

* Choose excel application
  IF I_EXCEL IS INITIAL.
    LS_EXCEL = GS_OLE_EXCEL.
  ELSE.
    LS_EXCEL = I_EXCEL.
  ENDIF.
  DATA: LW_FOOTER TYPE CHAR256.
* Set cells value
  CALL METHOD OF
      LS_EXCEL
      'ActiveSheet' = LS_ACTIVESHEET.
  CALL METHOD OF
      LS_ACTIVESHEET
      'PageSetup'    = LS_PAGESET.
  IF I_PAGESETUP-LEFTHEADER IS NOT INITIAL.
    SET PROPERTY OF LS_PAGESET 'LeftHeader'   = I_PAGESETUP-LEFTHEADER.
  ENDIF.
  IF I_PAGESETUP-CENTERHEADER IS NOT INITIAL.
  SET PROPERTY OF LS_PAGESET 'CenterHeader' = I_PAGESETUP-CENTERHEADER.
  ENDIF.
  IF I_PAGESETUP-RIGHTHEADER IS NOT INITIAL.
  SET PROPERTY OF LS_PAGESET 'RightHeader'  = I_PAGESETUP-RIGHTHEADER.
  ENDIF.
  IF I_PAGESETUP-LEFTFOOTER IS NOT INITIAL.
  SET PROPERTY OF LS_PAGESET 'LeftFooter'   = I_PAGESETUP-LEFTFOOTER.
  ENDIF.
  IF I_PAGESETUP-CENTERFOOTER IS NOT INITIAL.
  SET PROPERTY OF LS_PAGESET 'CenterFooter' = I_PAGESETUP-CENTERFOOTER.
  ENDIF.
  IF I_PAGESETUP-RIGHTFOOTER IS NOT INITIAL.
  SET PROPERTY OF LS_PAGESET 'RightFooter'  = I_PAGESETUP-RIGHTFOOTER.
  ENDIF.
*  SET PROPERTY OF LS_PAGESET 'RightFooter'  =
*                              '&"Times New Roman,Italic"&9Trang &P/&N'.

  FREE OBJECT LS_PAGESET.
  FREE OBJECT LS_ACTIVESHEET.





ENDFUNCTION.
