FUNCTION ZFM_SCR_PAI_PUT_ERR_FIELD.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_PROG) TYPE  SYCPROG DEFAULT SY-CPROG
*"     REFERENCE(I_DYNNR) TYPE  DYNNR DEFAULT SY-DYNNR
*"     REFERENCE(I_FIELDNAME) TYPE  CHAR61 OPTIONAL
*"     REFERENCE(I_ROW) TYPE  BAPI_LINE OPTIONAL
*"     REFERENCE(I_MSGID) TYPE  SYMSGID DEFAULT GC_MSG_CL
*"     REFERENCE(I_MTYPE) TYPE  BAPI_MTYPE DEFAULT 'E'
*"     REFERENCE(I_MSGNO) TYPE  ANY DEFAULT '002'
*"     REFERENCE(I_MSGV1) TYPE  ANY OPTIONAL
*"     REFERENCE(I_MSGV2) TYPE  ANY OPTIONAL
*"     REFERENCE(I_MSGV3) TYPE  ANY OPTIONAL
*"     REFERENCE(I_MSGV4) TYPE  ANY OPTIONAL
*"     VALUE(I_ERR_FIELD) TYPE  ZST_ERR_FIELD OPTIONAL
*"     REFERENCE(I_GETFTEXT) TYPE  XMARK OPTIONAL
*"     REFERENCE(I_COV_MSGV1) TYPE  XMARK OPTIONAL
*"--------------------------------------------------------------------
DATA: LW_FULLFIELD  TYPE CHAR100,
        LW_SCRTEXT_L  TYPE SCRTEXT_L,
        LT_ERR_FIELD  TYPE ZTT_ERR_FIELD,
        LS_FIELD_DB   TYPE ZTB_FIELD_DB,
        LW_TEXT       TYPE SYMSGV.
  FIELD-SYMBOLS: <LF_ERR_FIELD>    TYPE ANY.

*----------------------------------------------------*
  IF I_ERR_FIELD IS INITIAL.
    I_ERR_FIELD-DYNNR       = I_DYNNR.
    I_ERR_FIELD-FIELD       = I_FIELDNAME.
    I_ERR_FIELD-TYPE        = I_MTYPE.
    I_ERR_FIELD-ID          = I_MSGID.
    I_ERR_FIELD-NUMBER      = I_MSGNO.
    I_ERR_FIELD-ROW         = I_ROW.
    IF I_COV_MSGV1 = GC_XMARK.
      PERFORM CONVERT_ALPHA USING I_MSGV1
                            CHANGING LW_TEXT.
    ELSE.
      LW_TEXT = I_MSGV1.
    ENDIF.
    I_ERR_FIELD-MESSAGE_V1  = LW_TEXT.
    I_ERR_FIELD-MESSAGE_V2  = I_MSGV2.
    I_ERR_FIELD-MESSAGE_V3  = I_MSGV3.
    I_ERR_FIELD-MESSAGE_V4  = I_MSGV4.
  ENDIF.

  IF I_GETFTEXT = 'X'.
*   Get field value
    CONCATENATE '(' I_PROG ')' I_ERR_FIELD-FIELD INTO LW_FULLFIELD.
    ASSIGN (LW_FULLFIELD) TO <LF_ERR_FIELD>.
    CHECK SY-SUBRC IS INITIAL.

*   Get field label
    CALL FUNCTION 'ZFM_SCR_GET_FIELD_LABEL'
      EXPORTING
       I_PROG            = I_PROG
       I_DYNNR           = I_ERR_FIELD-DYNNR
       I_FIELDNAME       = I_ERR_FIELD-FIELD
       I_FIELD           = <LF_ERR_FIELD>
     IMPORTING
       E_SCRTEXT_L       = LW_SCRTEXT_L.

    I_ERR_FIELD-MESSAGE_V1  = LW_SCRTEXT_L.
    IF I_ERR_FIELD-MESSAGE_V2 IS INITIAL.
      I_ERR_FIELD-MESSAGE_V2 = <LF_ERR_FIELD>.
    ENDIF.
  ENDIF.
  READ TABLE GT_FIELD_DB INTO LS_FIELD_DB
    WITH KEY FIELDNAME = I_ERR_FIELD-FIELD.
  IF SY-SUBRC IS INITIAL.
    I_ERR_FIELD-FPOSI = LS_FIELD_DB-FPOSI.
  ENDIF.

  IF GW_CURR_CHECKROW IS NOT INITIAL.
*   Set row before is current check row
    I_ERR_FIELD-ROW = GW_CURR_CHECKROW.
    CLEAR: GW_CURR_CHECKROW.
  ENDIF.
  APPEND I_ERR_FIELD TO GT_ERR_FIELD.
*  APPEND I_ERR_FIELD TO LT_ERR_FIELD.
*  PERFORM ERROR_FIELDS_EXPORT
*    USING I_PROG
*          I_DYNNR
*          LT_ERR_FIELD
*          SPACE.





ENDFUNCTION.
