FUNCTION ZFM_SCR_PAI_PUT_HIGHLIGHT_F.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_REPID) TYPE  SYREPID DEFAULT SY-CPROG
*"     REFERENCE(I_DYNNR) TYPE  DYNNR DEFAULT SY-DYNNR
*"     REFERENCE(I_FIELDNAME) TYPE  CHAR61 OPTIONAL
*"     REFERENCE(I_ROW) TYPE  BAPI_LINE OPTIONAL
*"     VALUE(T_HIGHLIGHT_FIELD) TYPE  ZTT_ERR_FIELD OPTIONAL
*"--------------------------------------------------------------------
DATA:
      LS_HL_LABEL   TYPE ZST_ERR_FIELD,
      LT_HL_LABEL   TYPE TABLE OF ZST_ERR_FIELD,
      LS_HL_FIELD   TYPE ZST_ERR_FIELD,
      LS_FIELD_DB   TYPE ZTB_FIELD_DB,
      LW_SCRTEXT_L  TYPE SCRTEXT_L.
  FIELD-SYMBOLS:
    <LF_ERR_FIELD>    TYPE ANY.

  CHECK I_DYNNR IS NOT INITIAL.
  IF I_FIELDNAME IS NOT INITIAL.
    LS_HL_FIELD-DYNNR  = I_DYNNR.
    LS_HL_FIELD-FIELD  = I_FIELDNAME.
    LS_HL_FIELD-ROW    = I_ROW.
    APPEND LS_HL_FIELD TO T_HIGHLIGHT_FIELD.
  ENDIF.

  IF GT_FIELD_DB IS NOT INITIAL.
    LOOP AT T_HIGHLIGHT_FIELD INTO LS_HL_FIELD.
      READ TABLE GT_FIELD_DB INTO LS_FIELD_DB
        WITH KEY  REPID = I_REPID
                  DYNNR = I_DYNNR
                  FIELDNAME = LS_HL_FIELD-FIELD.
      IF SY-SUBRC IS INITIAL AND LS_FIELD_DB-LABELF IS NOT INITIAL.
        CLEAR: LS_HL_LABEL.
        LS_HL_LABEL-DYNNR  = I_DYNNR.
        LS_HL_LABEL-FIELD  = LS_FIELD_DB-LABELF.
        APPEND LS_HL_LABEL TO LT_HL_LABEL.
      ENDIF.
    ENDLOOP.
  ENDIF.
  APPEND LINES OF LT_HL_LABEL TO T_HIGHLIGHT_FIELD.

  PERFORM HIGHLIGHT_FIELDS_EXPORT
    USING I_REPID
          I_DYNNR
          T_HIGHLIGHT_FIELD.





ENDFUNCTION.
