FUNCTION-POOL ZFG_BM_POPUP.                 "MESSAGE-ID ..

INCLUDE ZIN_COMMONTOP.

DATA:
  BEGIN OF GT_SEL_INIT OCCURS 0,
    OPTION  TYPE SE16N_OPTION,
    LOW(1),
    HIGH(1),
  END OF GT_SEL_INIT.

TABLES: ZTB_BM_COND_NAME, ZST0_BM_COND_KEY_FLAT.
DATA:
  GO_ALV_COND     TYPE REF TO CL_GUI_ALV_GRID,
  GO_ALV_CHAR     TYPE REF TO CL_GUI_ALV_GRID,
  GT_ALV_DIMENS   TYPE ZTT0_BM_COND_DIM,
  GT_ALL_DIMENS   TYPE ZTT0_BM_COND_DIM,
  GT_RTABLE       TYPE TABLE OF TABNAMES,
  GT_CONDITION    TYPE TABLE OF ZST0_BM_SELOPT,
  GT_CONDNM       TYPE TABLE OF ZST0_BM_CONDNM,
  GS_SCR_COND_KEY TYPE ZST0_BM_COND_KEY.

* INCLUDE LZFG_BM_POPUPD...                  " Local class definition
CLASS  LCL_HANDLE_EVENT DEFINITION.
  PUBLIC SECTION.
    CLASS-METHODS: HANDLE_ALV_COND_F4
      FOR EVENT ONF4 OF CL_GUI_ALV_GRID
      IMPORTING E_FIELDNAME
                ES_ROW_NO
                ER_EVENT_DATA.
ENDCLASS.
