FUNCTION ZFM_GET_DESC_FOR_FIELD.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DES_FIELD) TYPE  FIELDNAME
*"     REFERENCE(I_DES_TFIELD) TYPE  FIELDNAME
*"     REFERENCE(I_SRC_FIELD) TYPE  FIELDNAME OPTIONAL
*"     REFERENCE(I_SRC_TFIELD) TYPE  FIELDNAME OPTIONAL
*"     REFERENCE(T_SRC_DATA) TYPE  ANY TABLE
*"     REFERENCE(I_SORT_DES_TAB) TYPE  XMARK DEFAULT 'X'
*"  CHANGING
*"     REFERENCE(T_DES_DATA) TYPE  ANY TABLE
*"--------------------------------------------------------------------
DATA:
    LR_DATA               TYPE REF TO DATA,
    LW_SRC_FIELD          TYPE FIELDNAME,
    LW_SRC_TFIELD         TYPE FIELDNAME.

  FIELD-SYMBOLS:
    <LF_DATA_SRC>         TYPE ANY,
    <LFT_DATA_SRC>        TYPE ANY TABLE,
    <LF_DATA_DES>         TYPE ANY,
    <LF_DES_FIELD>        TYPE ANY,
    <LF_DES_TFIELD>       TYPE ANY,
    <LF_SRC_FIELD>        TYPE ANY,
    <LF_SRC_TFIELD>       TYPE ANY.

* Init
  CREATE DATA LR_DATA LIKE T_SRC_DATA.
  ASSIGN LR_DATA->* TO <LFT_DATA_SRC>.
  CREATE DATA LR_DATA LIKE LINE OF T_SRC_DATA.
  ASSIGN LR_DATA->* TO <LF_DATA_SRC>.
  CREATE DATA LR_DATA LIKE LINE OF T_DES_DATA.
  ASSIGN LR_DATA->* TO <LF_DATA_DES>.

* Set source fields
  LW_SRC_FIELD = I_SRC_FIELD.
  LW_SRC_TFIELD = I_SRC_TFIELD.
  IF I_SRC_FIELD IS INITIAL.
    LW_SRC_FIELD = I_DES_FIELD.
  ENDIF.
  IF I_SRC_TFIELD IS INITIAL.
    LW_SRC_TFIELD = I_DES_TFIELD.
  ENDIF.

  <LFT_DATA_SRC> = T_SRC_DATA.
  SORT <LFT_DATA_SRC> BY (LW_SRC_FIELD).
  IF I_SORT_DES_TAB = 'X'.
    SORT T_DES_DATA BY (I_DES_FIELD).
  ENDIF.

  LOOP AT T_DES_DATA ASSIGNING <LF_DATA_DES>.
*   Get destination field and text field
    ASSIGN COMPONENT I_DES_FIELD OF STRUCTURE <LF_DATA_DES>
      TO <LF_DES_FIELD>.
    ASSIGN COMPONENT I_DES_TFIELD OF STRUCTURE <LF_DATA_DES>
      TO <LF_DES_TFIELD>.

*   Check desfield already read previous loop
    IF <LF_SRC_FIELD> IS NOT ASSIGNED
    OR <LF_SRC_FIELD> <> <LF_DES_FIELD>.
*     Search data from table list
      READ TABLE T_SRC_DATA ASSIGNING <LF_DATA_SRC>
        WITH KEY (LW_SRC_FIELD) = <LF_DES_FIELD>.
      IF SY-SUBRC IS INITIAL.
*       Get source field and text field
        ASSIGN COMPONENT LW_SRC_FIELD OF STRUCTURE <LF_DATA_SRC>
          TO <LF_SRC_FIELD>.
        ASSIGN COMPONENT LW_SRC_TFIELD OF STRUCTURE <LF_DATA_SRC>
          TO <LF_SRC_TFIELD>.
        MOVE <LF_SRC_TFIELD> TO <LF_DES_TFIELD>.
      ENDIF.
    ELSE.
      MOVE <LF_SRC_TFIELD> TO <LF_DES_TFIELD>.
    ENDIF.
  ENDLOOP.





ENDFUNCTION.
