FUNCTION-POOL ZFG_BM_SCRLOG.                "MESSAGE-ID ..

* INCLUDE LZFG_BM_SCRLOGD...                 " Local class definition

CONSTANTS:
  GC_VAR_SCR_LOG    TYPE RVARI_VNAM VALUE 'ZVAR_ALLOW_SCR_LOG'.
DATA:
  GW_ALLOW_SCR_LOG  TYPE XMARK,
  GT_TRAN           TYPE TABLE OF ZTB_BM_SL_TRAN,
  GT_STEP           TYPE TABLE OF ZTB_BM_SL_STEP,
  GT_SCRVL          TYPE TABLE OF ZTB_BM_SL_SCRVL.
