FUNCTION ZFM_SCR_ADD_ERR_FIELD.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(T_FIELD) TYPE  ZTT_ERR_FIELD OPTIONAL
*"     REFERENCE(I_FIELD) TYPE  ZST_ERR_FIELD OPTIONAL
*"     REFERENCE(I_CPROG) TYPE  CPROG DEFAULT SY-CPROG
*"     REFERENCE(I_AUTO_STOP) TYPE  XMARK DEFAULT 'X'
*"     REFERENCE(I_DYNNR) TYPE  DYNNR DEFAULT SY-DYNNR
*"     REFERENCE(I_GETFTEXT) TYPE  XMARK OPTIONAL
*"--------------------------------------------------------------------
DATA:
      LS_FIELD      TYPE ZST_ERR_FIELD,
      LT_FIELD      TYPE TABLE OF ZST_ERR_FIELD,
      LW_FULLFIELD  TYPE CHAR100,
      LW_SCRTEXT_L  TYPE SCRTEXT_L.
  FIELD-SYMBOLS:
    <LF_ERR_FIELD>    TYPE ANY.

  LS_FIELD = I_FIELD.
  IF LS_FIELD-DYNNR IS INITIAL.
    LS_FIELD-DYNNR   = I_DYNNR.
  ENDIF.

* Get field value
  CONCATENATE '(' I_CPROG ')' LS_FIELD-FIELD INTO LW_FULLFIELD.
  ASSIGN (LW_FULLFIELD) TO <LF_ERR_FIELD>.

  IF I_FIELD IS SUPPLIED
  AND ( LS_FIELD-TYPE IS INITIAL
     OR LS_FIELD-ID IS INITIAL
     OR LS_FIELD-NUMBER IS INITIAL ).
    LS_FIELD-TYPE    = 'E'.
    LS_FIELD-ID      = GC_MSG_CL.
    LS_FIELD-NUMBER  = '002'.       "Field value invalid

*   Get field label
    PERFORM GET_FIELD_LABEL
      USING  LS_FIELD-FIELD
             <LF_ERR_FIELD>
             I_CPROG
             I_DYNNR
      CHANGING LW_SCRTEXT_L.
    LS_FIELD-MESSAGE_V1 = LW_SCRTEXT_L.
    LS_FIELD-MESSAGE_V2 = <LF_ERR_FIELD>.
  ENDIF.

  IF I_GETFTEXT = 'X'.
*   Get field label
    PERFORM GET_FIELD_LABEL
      USING  LS_FIELD-FIELD
             <LF_ERR_FIELD>
             I_CPROG
             I_DYNNR
      CHANGING LW_SCRTEXT_L.
    LS_FIELD-MESSAGE_V1 = LW_SCRTEXT_L.
  ENDIF.

  IF I_FIELD IS NOT INITIAL.
    APPEND LS_FIELD TO LT_FIELD.
*   Export error fields to memory name:
*   "[ProgramName][ScreenNo]_ERR_FIELDS"
    PERFORM ERROR_FIELDS_EXPORT
      USING I_CPROG I_DYNNR LT_FIELD I_AUTO_STOP.
  ENDIF.
  IF T_FIELD IS NOT INITIAL.
    APPEND LINES OF T_FIELD TO LT_FIELD.
*   Export error fields to memory name:
*   "[ProgramName][ScreenNo]_ERR_FIELDS"
    PERFORM ERROR_FIELDS_EXPORT
      USING I_CPROG I_DYNNR LT_FIELD I_AUTO_STOP.
  ENDIF.





ENDFUNCTION.
