FUNCTION ZFM_JBCF_GET_CONFIG.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  EXPORTING
*"     REFERENCE(T_JBCF_JOB_ALL) TYPE  ZTT_JBCF_JOB_ALL
*"--------------------------------------------------------------------
DATA:
    LT_JBCF_JOB     TYPE TABLE OF ZTB_JBCF_JOB,
    LT_JBCF_JSTEP   TYPE TABLE OF ZTB_JBCF_JSTEP,
    LS_JBCF_JOB     TYPE ZTB_JBCF_JOB,
    LS_JBCF_JOB_ALL TYPE ZST_JBCF_JOB,
    LS_JBCF_JSTEP   TYPE ZTB_JBCF_JSTEP.

  IF GT_JBCF_JOB_ALL IS NOT INITIAL.
    T_JBCF_JOB_ALL = GT_JBCF_JOB_ALL.
    RETURN.
  ENDIF.
* Get list job
  SELECT *
    FROM ZTB_JBCF_JOB
    INTO TABLE LT_JBCF_JOB
   WHERE ACTIVE = GC_XMARK.

* Get list step
  SELECT *
    FROM ZTB_JBCF_JSTEP
    INTO TABLE LT_JBCF_JSTEP.

* Aggregate
  LOOP AT LT_JBCF_JOB INTO LS_JBCF_JOB.
    CLEAR: LS_JBCF_JOB_ALL.
    MOVE-CORRESPONDING LS_JBCF_JOB TO LS_JBCF_JOB_ALL.
    LS_JBCF_JOB_ALL-STEPS = LT_JBCF_JSTEP.
    DELETE LS_JBCF_JOB_ALL-STEPS WHERE JOBNAME <> LS_JBCF_JOB-JOBNAME.
    CHECK: LS_JBCF_JOB_ALL-STEPS[] IS NOT INITIAL.
    APPEND LS_JBCF_JOB_ALL TO GT_JBCF_JOB_ALL.
  ENDLOOP.

  T_JBCF_JOB_ALL[] = GT_JBCF_JOB_ALL[].





ENDFUNCTION.
