FUNCTION ZFM_DATA_ORIGINAL_GET.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(T_TABLE_CURRENT) TYPE  ANY TABLE
*"     REFERENCE(I_STRUCTURE) TYPE  TABNAME OPTIONAL
*"     REFERENCE(T_FIELDCAT) TYPE  LVC_T_FCAT OPTIONAL
*"  EXPORTING
*"     REFERENCE(T_TABLE_ORIGINAL) TYPE  ANY TABLE
*"  EXCEPTIONS
*"      NO_STRUCTURE
*"      CONFLICT_STRUCTURE
*"      NO_DATA
*"--------------------------------------------------------------------

  PERFORM CHECK_STRUCTURE
    USING     I_STRUCTURE T_FIELDCAT.

  PERFORM GET_FIELDCAT
    USING     I_STRUCTURE T_FIELDCAT.

  IF 1 = 2.
    PERFORM BUILD_WHERE_CLAUSE  USING     T_TABLE_CURRENT.
    PERFORM GET_DATA_BY_CLAUSE  CHANGING  T_TABLE_ORIGINAL.
  ELSE.
    PERFORM GET_ORIGINAL_DATA_JOININTAB
      USING T_TABLE_CURRENT
      CHANGING T_TABLE_ORIGINAL.
  ENDIF.





ENDFUNCTION.
