FUNCTION ZFM_RP_OUTPUT_EXCEL.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_REPORT) TYPE  PROGRAMM DEFAULT SY-CPROG
*"     REFERENCE(I_TABNAME) TYPE  TABNAME OPTIONAL
*"     REFERENCE(I_DATA)
*"     REFERENCE(I_LOGICALFILE) TYPE  ESEFTAPPL
*"     REFERENCE(I_DEFAULT_FILENAME) TYPE  STRING OPTIONAL
*"     REFERENCE(I_NO_ASK) TYPE  XMARK OPTIONAL
*"     REFERENCE(I_LARGE_FILE) TYPE  XMARK OPTIONAL
*"     REFERENCE(T_EXCEL_LAYOUT) TYPE  ZTT_EXCEL_LAYOUT OPTIONAL
*"----------------------------------------------------------------------
DATA:
    LT_EXCEL_LAYOUT  TYPE TABLE OF ZTB_EXCEL_LAYOUT,
    LS_EXCEL_LAYOUT  TYPE ZTB_EXCEL_LAYOUT,
    LT_EXCEL_EX      TYPE TABLE OF ZST_EXCEL_EXP,
    LS_PAGESETUP     TYPE ZST_EXCEL_PAGESETUP.
  FIELD-SYMBOLS:
    <LF_DATA>     TYPE ANY,
    <LFT_ITEMS>   TYPE ANY TABLE.

  CLEAR: LT_EXCEL_EX[].

  IF T_EXCEL_LAYOUT[] IS NOT INITIAL.
    LT_EXCEL_LAYOUT = T_EXCEL_LAYOUT[].
  ELSE.
    SELECT *
      INTO TABLE LT_EXCEL_LAYOUT
      FROM ZTB_EXCEL_LAYOUT
     WHERE REPORT  = I_REPORT.
    SORT LT_EXCEL_LAYOUT BY ROW_POS COL_POS.
  ENDIF.

  CALL FUNCTION 'ZFM_FILE_EXCEL_GET_HEADER'
    EXPORTING
      I_REPORT       = I_REPORT
      I_TABNAME      = I_TABNAME
      I_HEADER       = I_DATA
      T_EXCEL_LAYOUT = LT_EXCEL_LAYOUT
      I_LARGE_FILE   = I_LARGE_FILE
    IMPORTING
      E_PAGESETUP    = LS_PAGESETUP
      T_EXCEL_EXP    = LT_EXCEL_EX.

  IF I_LARGE_FILE = GC_XMARK.
    CALL FUNCTION 'ZFM_FILE_EXCEL_GET_ITEMS_NUM'
      EXPORTING
        I_DATA         = I_DATA
        T_EXCEL_LAYOUT = LT_EXCEL_LAYOUT
      IMPORTING
        T_EXCEL_EXP    = LT_EXCEL_EX.

    CALL FUNCTION 'ZFM_FILE_EXCEL_EXPORT_NUM'
      EXPORTING
        I_LOGICALFILE       = I_LOGICALFILE
        T_SQUARE_DATA       = LT_EXCEL_EX
        I_PAGESETUP         = LS_PAGESETUP
        I_DEFAULT_FILENAME  = I_DEFAULT_FILENAME
        I_NO_ASK            = I_NO_ASK
      EXCEPTIONS
        SAVE_TEMPLATE_ERR   = 1
        OPEN_FILE_ERR       = 2
        EXPORT_ERR          = 3
        OTHERS              = 4.
  ELSE.
    CALL FUNCTION 'ZFM_FILE_EXCEL_GET_ITEMS'
      EXPORTING
        I_DATA         = I_DATA
        T_EXCEL_LAYOUT = LT_EXCEL_LAYOUT
      IMPORTING
        T_EXCEL_EXP    = LT_EXCEL_EX.

    IF SY-UNAME <> 'TUANBA'.
      CALL FUNCTION 'ZFM_FILE_EXCEL_EXPORT'
        EXPORTING
          I_LOGICALFILE       = I_LOGICALFILE
          T_SQUARE_DATA       = LT_EXCEL_EX
          I_PAGESETUP         = LS_PAGESETUP
          I_DEFAULT_FILENAME  = I_DEFAULT_FILENAME
          I_NO_ASK            = I_NO_ASK
        EXCEPTIONS
          SAVE_TEMPLATE_ERR   = 1
          OPEN_FILE_ERR       = 2
          EXPORT_ERR          = 3
          OTHERS              = 4.
    ELSE.
      CALL FUNCTION 'ZFM_FILE_EXCEL_EXPORT2'
        EXPORTING
          I_LOGICALFILE           = I_LOGICALFILE
          T_SQUARE_DATA           = LT_EXCEL_EX
          T_EXCEL_LAYOUT          = LT_EXCEL_LAYOUT
          I_DATA                  = I_DATA
       EXCEPTIONS
         SAVE_TEMPLATE_ERR       = 1
         OPEN_FILE_ERR           = 2
         EXPORT_ERR              = 3
         OTHERS                  = 4.
    ENDIF.
  ENDIF.

  CASE SY-SUBRC.
    WHEN 1.
      MESSAGE S003 DISPLAY LIKE GC_MTYPE_E.
    WHEN 2.
      MESSAGE S004 DISPLAY LIKE GC_MTYPE_E.
    WHEN 3.
      MESSAGE S005 DISPLAY LIKE GC_MTYPE_E.
    WHEN 4.
      MESSAGE S006 DISPLAY LIKE GC_MTYPE_E.
  ENDCASE.





ENDFUNCTION.
