FUNCTION ZFM_BM_DF_MAP_ERRCODE.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DF_FIELD) TYPE  ZST_BM_DF_FIELD
*"     REFERENCE(I_RETURN) TYPE  BAPIRET2
*"     REFERENCE(I_EINIT) TYPE  ZDD_BM_DF_EINIT OPTIONAL
*"     REFERENCE(I_ELENG) TYPE  ZDD_BM_DF_ELEN OPTIONAL
*"     REFERENCE(I_EFMAT) TYPE  ZDD_BM_DF_EFMAT OPTIONAL
*"     REFERENCE(I_EVLDB) TYPE  ZDD_BM_DF_EVLDB OPTIONAL
*"     REFERENCE(I_MSGID) TYPE  MSGID OPTIONAL
*"     REFERENCE(I_ENUMB) TYPE  MSGNO OPTIONAL
*"  EXPORTING
*"     REFERENCE(ET_FIELD_EC) TYPE  ZTT_BM_DF_FIELD_EC
*"----------------------------------------------------------------------

  DATA:
    LS_FIELD_EC               TYPE ZST_BM_DF_FIELD_EC,
    LS_DF_TYPEC               TYPE ZTB_BM_DF_TYP_EC,
    LS_DF_ECODE               TYPE ZTB_BM_DF_EC.

  IF I_EINIT IS NOT INITIAL
  OR I_ELENG IS NOT INITIAL
  OR I_EFMAT IS NOT INITIAL
  OR I_EVLDB IS NOT INITIAL.
*   Get error code
    READ TABLE GT_DF_TYPEC INTO LS_DF_TYPEC
      WITH KEY TYPEID = I_DF_FIELD-TYPEID
               EINIT  = I_EINIT
               ELENG  = I_ELENG
               EFMAT  = I_EFMAT
               EVLDB  = I_EVLDB.
    IF SY-SUBRC IS INITIAL.
      MOVE-CORRESPONDING I_DF_FIELD TO LS_FIELD_EC.
      MOVE-CORRESPONDING LS_DF_TYPEC TO LS_FIELD_EC.
      MOVE-CORRESPONDING I_RETURN TO LS_FIELD_EC.
      LS_FIELD_EC-RETURN = I_RETURN.
      APPEND LS_FIELD_EC TO ET_FIELD_EC.
    ELSE.
      READ TABLE GT_DF_ECODE INTO LS_DF_ECODE
        WITH KEY ELIST  = I_DF_FIELD-ELIST
                 EINIT  = I_EINIT
                 ELENG  = I_ELENG
                 EFMAT  = I_EFMAT
                 EVLDB  = I_EVLDB.
      IF SY-SUBRC IS INITIAL.
        MOVE-CORRESPONDING I_DF_FIELD TO LS_FIELD_EC.
        MOVE-CORRESPONDING LS_DF_ECODE TO LS_FIELD_EC.
        MOVE-CORRESPONDING I_RETURN TO LS_FIELD_EC.
        LS_FIELD_EC-RETURN = I_RETURN.
        APPEND LS_FIELD_EC TO ET_FIELD_EC.
      ENDIF.
    ENDIF.
  ELSE.
*   Get error code
    READ TABLE GT_DF_TYPEC INTO LS_DF_TYPEC
      WITH KEY TYPEID = I_DF_FIELD-TYPEID
               MSGID  = I_RETURN-ID
               ENUMB  = I_RETURN-NUMBER.
    IF SY-SUBRC IS INITIAL.
      MOVE-CORRESPONDING I_DF_FIELD TO LS_FIELD_EC.
      MOVE-CORRESPONDING LS_DF_TYPEC TO LS_FIELD_EC.
      MOVE-CORRESPONDING I_RETURN TO LS_FIELD_EC.
      LS_FIELD_EC-RETURN = I_RETURN.
      APPEND LS_FIELD_EC TO ET_FIELD_EC.
    ELSE.
      READ TABLE GT_DF_ECODE INTO LS_DF_ECODE
        WITH KEY ELIST  = I_DF_FIELD-ELIST
                 MSGID  = I_RETURN-ID
                 ENUMB  = I_RETURN-NUMBER.
      IF SY-SUBRC IS INITIAL.
        MOVE-CORRESPONDING I_DF_FIELD TO LS_FIELD_EC.
        MOVE-CORRESPONDING LS_DF_ECODE TO LS_FIELD_EC.
        MOVE-CORRESPONDING I_RETURN TO LS_FIELD_EC.
        LS_FIELD_EC-RETURN = I_RETURN.
        APPEND LS_FIELD_EC TO ET_FIELD_EC.
      ENDIF.
    ENDIF.
  ENDIF.

ENDFUNCTION.
