FUNCTION ZFM_BM_ALV_ITEM_DETAIL.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IT_FCAT) TYPE  LVC_T_FCAT
*"     REFERENCE(IS_DETAIL)
*"----------------------------------------------------------------------
  DATA:
    LT_FCAT   TYPE LVC_T_FCAT,
    LS_FCAT   TYPE LVC_S_FCAT,
    LS_LAYO   TYPE LVC_S_LAYO,
*    LT_DET                    TYPE LVC_T_DETM,
*    LS_DET                    TYPE LVC_S_DETM,
    LS_DETAIL TYPE ZST_LVC_S_DETA,
    LT_DETAIL TYPE TABLE OF ZST_LVC_S_DETA,
    LW_WHERE  TYPE STRING.
  FIELD-SYMBOLS:
    <LF_NEST_VAL>             TYPE ANY.

  LOOP AT IT_FCAT INTO LS_FCAT.
    CLEAR: LS_DETAIL.
    CHECK LS_FCAT-TECH IS INITIAL.
    LS_DETAIL-COLUMNTEXT = LS_FCAT-SCRTEXT_L.
    LS_DETAIL-FIELDNAME = LS_FCAT-FIELDNAME.
*    IF LS_FCAT-SCRTEXT_L IS INITIAL.
*      LS_DETAIL-COLUMNTEXT = LS_FCAT-FIELDNAME.
*    ELSE.
*      CONCATENATE LS_FCAT-FIELDNAME LS_FCAT-SCRTEXT_L
*      INTO LS_DETAIL_TAB-COLUMNTEXT SEPARATED BY '-' RESPECTING BLANKS.
*    ENDIF.
    ASSIGN COMPONENT LS_FCAT-FIELDNAME OF
      STRUCTURE IS_DETAIL TO <LF_NEST_VAL>.

    MOVE <LF_NEST_VAL> TO LS_DETAIL-VALUE.
    CONDENSE LS_DETAIL-VALUE.
    APPEND LS_DETAIL TO LT_DETAIL.
  ENDLOOP.

*  MOVE LT_DETAIL TO LS_DET-DETAILTAB.
*  APPEND LS_DET TO LT_DET.

  CLEAR LT_FCAT.
  CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
    EXPORTING
      I_STRUCTURE_NAME   = 'ZST_LVC_S_DETA'
      I_INTERNAL_TABNAME = 'ZST_LVC_S_DETA'
    CHANGING
      CT_FIELDCAT        = LT_FCAT.
  LS_LAYO-CWIDTH_OPT = GC_XMARK.

  CALL FUNCTION 'ZFM_ALV_DISPLAY'
    EXPORTING
      I_STRUCTURE_NAME      = 'ZST_LVC_S_DETA'
      IT_FIELDCAT           = LT_FCAT
      IS_LAYOUT_LVC         = LS_LAYO
      I_SCREEN_START_COLUMN = 5
      I_SCREEN_START_LINE   = 3
      I_SCREEN_END_COLUMN   = 90
      I_SCREEN_END_LINE     = 25
    TABLES
      T_OUTTAB              = LT_DETAIL.

*  CALL FUNCTION 'LVC_ITEM_DETAIL'
*    EXPORTING
*      IT_FIELDCATALOG       = LT_FCAT
*      IS_LAYOUT             = LS_LAYO
*      I_SCREEN_START_COLUMN = 5
*      I_SCREEN_START_LINE   = 5
*      I_SCREEN_END_COLUMN   = 100
*      I_SCREEN_END_LINE     = 20
*    TABLES
*      T_OUTTAB              = LT_DET.





ENDFUNCTION.
