FUNCTION ZFM_RP_ALV_GET_ITEMS_FCAT.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_REPORT) TYPE  PROGRAMM DEFAULT SY-CPROG
*"     REFERENCE(T_ITEMS) TYPE  TABLE
*"     REFERENCE(I_ITEMS_FNAME) TYPE  FIELDNAME DEFAULT 'ITEMS'
*"     REFERENCE(I_ALV_LAYOUT_ITEM) TYPE  ZTB_BM_ALV_LAYO OPTIONAL
*"     REFERENCE(I_NO_ZERO) TYPE  XMARK
*"  EXPORTING
*"     REFERENCE(T_FIELDCAT) TYPE  LVC_T_FCAT
*"--------------------------------------------------------------------
DATA:
    LS_ALV_ITM      TYPE ZTB_BM_ALV_LAYO,
    LW_ITEMS_TYPENM TYPE DDOBJNAME,
    LS_DD40V        TYPE DD40V.
  FIELD-SYMBOLS:
    <LF_FIELDCAT>   TYPE LVC_S_FCAT.

* Get structure of line item
  DESCRIBE FIELD T_ITEMS HELP-ID LW_ITEMS_TYPENM.
  CALL FUNCTION 'DDIF_TTYP_GET'
    EXPORTING
      NAME     = LW_ITEMS_TYPENM
    IMPORTING
      DD40V_WA = LS_DD40V
    EXCEPTIONS
      OTHERS   = 2.

* Get ALV layout
  LS_ALV_ITM = I_ALV_LAYOUT_ITEM.
  IF LS_ALV_ITM IS INITIAL.
    SELECT SINGLE *
      INTO LS_ALV_ITM
      FROM ZTB_BM_ALV_LAYO
     WHERE REPORT  = I_REPORT
       AND FNAME = I_ITEMS_FNAME
       AND IS_ITEM = 'X'.
  ENDIF.

* Get fieldcat of Items table
  CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
    EXPORTING
      I_STRUCTURE_NAME   = LS_DD40V-ROWTYPE
      I_INTERNAL_TABNAME = LS_DD40V-ROWTYPE
    CHANGING
      CT_FIELDCAT        = T_FIELDCAT
    EXCEPTIONS
      OTHERS             = 3.
* Set no output for field has position > No column output in
* config ZTC_PROG
  LOOP AT T_FIELDCAT ASSIGNING <LF_FIELDCAT>
    WHERE COL_POS > LS_ALV_ITM-COLS.
    <LF_FIELDCAT>-NO_OUT = 'X'.
    IF I_NO_ZERO IS NOT INITIAL.
      <LF_FIELDCAT>-NO_ZERO = 'X'.
    ENDIF.
  ENDLOOP.





ENDFUNCTION.
