FUNCTION ZFM_BM_SIMPLE_TREE_FIRST_DISP.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_TREE_STR) TYPE  ZST_TREE_STR
*"     REFERENCE(I_SHOW) TYPE  XMARK DEFAULT 'X'
*"     REFERENCE(I_SIDE) TYPE  I OPTIONAL
*"     REFERENCE(I_EXTENSION) TYPE  I OPTIONAL
*"     REFERENCE(I_CONTAINER) TYPE REF TO CL_GUI_CUSTOM_CONTAINER
*"         OPTIONAL
*"  EXPORTING
*"     REFERENCE(E_TREE_CONTROL) TYPE REF TO CL_GUI_SIMPLE_TREE
*"     REFERENCE(T_NODES) TYPE  ZTT_TREESNODE
*"     REFERENCE(E_DOCK_CONTAINER) TYPE
*"EF TO CL_GUI_DOCKING_CONTAINER
*"  CHANGING
*"     REFERENCE(T_TREE_TAB) TYPE  ANY TABLE
*"--------------------------------------------------------------------
GO_CONTAINER = I_CONTAINER.

* Save data for tree
  PERFORM PUSH_TREE_DATA USING T_TREE_TAB I_TREE_STR.

* Create node
  PERFORM MAP_DATA_TO_NODE USING I_TREE_STR.

* Build tree container
  PERFORM BUILD_TREE  USING I_SHOW I_SIDE I_EXTENSION .

* Export
  E_TREE_CONTROL = GO_TREE.
  T_NODES        = GT_NODES.
  T_TREE_TAB     = <GFT_TREE_DATA>.





ENDFUNCTION.
