FUNCTION ZFM_DOI_EXCEL_DATA_EXPORT.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_SPREADSHEET) TYPE REF TO I_OI_SPREADSHEET
*"     REFERENCE(I_SHEETNAME) TYPE  SOI_FIELD_NAME
*"  EXPORTING
*"     REFERENCE(E_LINES) TYPE  I
*"  TABLES
*"      T_EXCEL TYPE  SOI_GENERIC_TABLE
*"  EXCEPTIONS
*"      EXPORT_ERR
*"--------------------------------------------------------------------
DATA:
    LO_ERROR        TYPE REF TO I_OI_ERROR,
    LW_RETCODE      TYPE SOI_RET_STRING,
    LT_SHEETS       TYPE SOI_SHEETS_TABLE,
    LS_SHEETS       TYPE SOI_SHEETS,
    LT_EXCEL_DATA   TYPE SOI_GENERIC_TABLE,
    LS_DIMENS       TYPE SOI_DIMENSION_ITEM,
    LT_DIMENS       TYPE TABLE OF SOI_DIMENSION_ITEM,
    LT_RANGE_FULL   TYPE SOI_FULL_RANGE_TABLE,
    LS_RANGE_FULL   LIKE LINE OF LT_RANGE_FULL,
    LT_RANGES       TYPE SOI_RANGE_LIST,
    LS_RANGE        LIKE LINE OF LT_RANGES,
    LT_HDR_FORMAT   TYPE SOI_FORMAT_TABLE,
    LS_FORMAT       TYPE SOI_FORMAT_ITEM,
    LT_ITM_FORMAT   TYPE SOI_FORMAT_TABLE,
    LW_BOLD_ROW     TYPE I.

  FIELD-SYMBOLS:
    <LF_DATA>       TYPE ANY,
    <LF_VALUE>      TYPE ANY,
    <LF_EXCEL_DATA> TYPE SOI_GENERIC_ITEM.

  CHECK T_EXCEL[] IS NOT INITIAL.
  LT_EXCEL_DATA[] = T_EXCEL[].

  CLEAR: LT_DIMENS[].
  CALL FUNCTION 'ZFM_FILE_EXCEL_DATA_GETDIMENS'
    IMPORTING
      E_DIMENSION  = LS_DIMENS
    TABLES
      T_EXCEL_DATA = LT_EXCEL_DATA.
  APPEND LS_DIMENS TO LT_DIMENS.

* Change demension row
  LOOP AT LT_EXCEL_DATA ASSIGNING <LF_EXCEL_DATA>.
    <LF_EXCEL_DATA>-ROW     = <LF_EXCEL_DATA>-ROW - LS_DIMENS-ROW + 1.
    <LF_EXCEL_DATA>-COLUMN  = <LF_EXCEL_DATA>-COLUMN -
                              LS_DIMENS-COLUMN + 1.
    CONDENSE: <LF_EXCEL_DATA>-ROW, <LF_EXCEL_DATA>-COLUMN.
  ENDLOOP.
** Add sheet.
* LOOP AT LT_EXCEL_DATA ASSIGNING <LF_EXCEL_DATA>.
*       CALL METHOD I_SPREADSHEET->ADD_SHEET
*       EXPORTING
*         NAME  = I_SHEETNAME
*       IMPORTING
*         ERROR = LO_ERROR.
** Activate a Sheet
*  CALL METHOD I_SPREADSHEET->SELECT_SHEET
*    EXPORTING
*      NAME  = I_SHEETNAME
*    IMPORTING
*      ERROR = LO_ERROR.
*  IF LO_ERROR->HAS_FAILED = 'X'.
*    PERFORM CLOSE_DOCUMENT.
*    RETURN.
*  ENDIF.
*ENDLOOP.
* Activate a Sheet
  CALL METHOD I_SPREADSHEET->SELECT_SHEET
    EXPORTING
      NAME  = I_SHEETNAME
    IMPORTING
      ERROR = LO_ERROR.
  IF LO_ERROR->HAS_FAILED = 'X'.
    PERFORM CLOSE_DOCUMENT.
    RETURN.
  ENDIF.

* Set range data
  CALL METHOD I_SPREADSHEET->SET_RANGES_DATA
    EXPORTING
      NO_FLUSH  = ''
      RANGESDEF = LT_DIMENS
      RANGES    = LT_RANGES
      CONTENTS  = LT_EXCEL_DATA
    IMPORTING
      ERROR     = LO_ERROR
      RETCODE   = LW_RETCODE.
  IF LO_ERROR->HAS_FAILED = 'X'.
    RAISE EXPORT_ERR.
  ENDIF.

  E_LINES = LS_DIMENS-ROWS.





ENDFUNCTION.
