FUNCTION ZFM_SHOW_PROGRESS_INDICATOR.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_CURRENT_RECORD) TYPE  NUMC10
*"     VALUE(I_TOTAL_RECORD) TYPE  NUMC10 OPTIONAL
*"--------------------------------------------------------------------
DATA:
    LW_PERCEN   TYPE NUMC3,
    LW_TEXT     TYPE TEXT200,
    LW_REC_STR  TYPE TEXT50.

  LW_TEXT = TEXT-011.

  IF I_TOTAL_RECORD IS INITIAL.
    SHIFT I_CURRENT_RECORD LEFT DELETING LEADING '0'.
    REPLACE '&1' IN LW_TEXT WITH I_CURRENT_RECORD.
  ELSE.
    LW_PERCEN = I_CURRENT_RECORD * 100 / I_TOTAL_RECORD.
    SHIFT I_CURRENT_RECORD LEFT DELETING LEADING '0'.
    SHIFT I_TOTAL_RECORD LEFT DELETING LEADING '0'.
    CONCATENATE I_CURRENT_RECORD I_TOTAL_RECORD
      INTO LW_REC_STR SEPARATED BY'/'.
    REPLACE '&1' IN LW_TEXT WITH LW_REC_STR.
  ENDIF.

  CALL FUNCTION 'SAPGUI_PROGRESS_INDICATOR'
    EXPORTING
      PERCENTAGE       = LW_PERCEN
      TEXT             = LW_TEXT.





ENDFUNCTION.
