FUNCTION ZFM_BM_POPUP_CONDTIONS.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_CONDNM) TYPE  ZDD_BM_CONDNM OPTIONAL
*"     REFERENCE(I_CONDKEY) TYPE  ZDD_BM_CONDKEY OPTIONAL
*"----------------------------------------------------------------------

  READ TABLE GT_CONDNM ASSIGNING FIELD-SYMBOL(<LF_CONDNM>)
    WITH KEY CONDNM = I_CONDNM BINARY SEARCH.
  IF SY-SUBRC IS INITIAL.
    READ TABLE <LF_CONDNM>-KEYS INTO GS_SCR_COND_KEY
      WITH KEY CONDKEY = I_CONDKEY BINARY SEARCH.
    IF SY-SUBRC IS INITIAL.
      MOVE-CORRESPONDING GS_SCR_COND_KEY TO ZST0_BM_COND_KEY_FLAT.

*     Convert and colapse condition to alv
      PERFORM 9999_CONV_CONDITION_DB2ALV
        USING GS_SCR_COND_KEY-DETAIL
        CHANGING GT_CONDITION.
    ELSE.
      ZST0_BM_COND_KEY_FLAT-CONDKEY = I_CONDKEY.
    ENDIF.

    GT_ALL_DIMENS = <LF_CONDNM>-DIMENSIONS.
    GT_ALV_DIMENS = <LF_CONDNM>-DIMENSIONS.
    MOVE-CORRESPONDING <LF_CONDNM> TO ZTB_BM_COND_NAME.
    CALL SCREEN 0100 STARTING AT 5 5.
  ENDIF.



ENDFUNCTION.
