FUNCTION ZFM_DATA_GET_FIELD_NOT_BLANK.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_DATA) TYPE  ANY
*"     REFERENCE(I_STRUCTURE) TYPE  TABNAME
*"  EXPORTING
*"     REFERENCE(E_FIRST_FIELD) TYPE  LVC_S_FCAT
*"     REFERENCE(T_FIELD_NOT_BLANK) TYPE  LVC_T_FCAT
*"  EXCEPTIONS
*"      NO_STRUCTURE
*"--------------------------------------------------------------------
DATA:
    LT_FIELDCAT     TYPE LVC_T_FCAT,
    LS_FIELDCAT     TYPE LVC_S_FCAT.
  FIELD-SYMBOLS:
    <LF_FIELD_VALUE>  TYPE ANY.

* Init
  CLEAR: E_FIRST_FIELD, T_FIELD_NOT_BLANK[].

  IF I_STRUCTURE IS INITIAL.
    RAISE NO_STRUCTURE.
  ENDIF.

* Get table name and field category
  CALL FUNCTION 'LVC_FIELDCATALOG_MERGE'
    EXPORTING
      I_STRUCTURE_NAME       = I_STRUCTURE
      I_INTERNAL_TABNAME     = I_STRUCTURE
    CHANGING
      CT_FIELDCAT            = LT_FIELDCAT
    EXCEPTIONS
      INCONSISTENT_INTERFACE = 1
      PROGRAM_ERROR          = 2
      OTHERS                 = 3.

  LOOP AT LT_FIELDCAT INTO LS_FIELDCAT.
    ASSIGN COMPONENT LS_FIELDCAT-FIELDNAME OF STRUCTURE I_DATA
      TO <LF_FIELD_VALUE>.
    IF SY-SUBRC IS INITIAL AND <LF_FIELD_VALUE> IS NOT INITIAL.
      APPEND LS_FIELDCAT TO T_FIELD_NOT_BLANK.
      IF E_FIRST_FIELD IS INITIAL.
        E_FIRST_FIELD = LS_FIELDCAT.
      ENDIF.
    ENDIF.
  ENDLOOP.





ENDFUNCTION.
