FUNCTION ZFM_DATA_CONCATENATE.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_TEXT1) OPTIONAL
*"     VALUE(I_TEXT2) OPTIONAL
*"     VALUE(I_TEXT3) OPTIONAL
*"     VALUE(I_TEXT4) OPTIONAL
*"     VALUE(I_TEXT5) OPTIONAL
*"     VALUE(I_TEXT6) OPTIONAL
*"     VALUE(I_TEXT7) OPTIONAL
*"     VALUE(I_TEXT8) OPTIONAL
*"     VALUE(I_TEXT9) OPTIONAL
*"     VALUE(I_TEXT10) OPTIONAL
*"     VALUE(I_SEPARATOR) DEFAULT ', '
*"  EXPORTING
*"     REFERENCE(E_TEXT)
*"--------------------------------------------------------------------
DATA:
    BEGIN OF LT_TEXT OCCURS 0,
      TEXT     TYPE CHAR100,
    END OF LT_TEXT,
    LW_TEXT     TYPE CHAR100,
    LW_TEXT_STR TYPE STRING.

  CONDENSE: I_TEXT1, I_TEXT2, I_TEXT3, I_TEXT4, I_TEXT5, I_TEXT6,
            I_TEXT7, I_TEXT8, I_TEXT9, I_TEXT10.
  APPEND I_TEXT1 TO LT_TEXT[].
  APPEND I_TEXT2 TO LT_TEXT[].
  APPEND I_TEXT3 TO LT_TEXT[].
  APPEND I_TEXT4 TO LT_TEXT[].
  APPEND I_TEXT5 TO LT_TEXT[].
  APPEND I_TEXT6 TO LT_TEXT[].
  APPEND I_TEXT7 TO LT_TEXT[].
  APPEND I_TEXT8 TO LT_TEXT[].
  APPEND I_TEXT9 TO LT_TEXT[].
  APPEND I_TEXT10 TO LT_TEXT[].

  DELETE LT_TEXT WHERE TEXT IS INITIAL.
  CONCATENATE LINES OF LT_TEXT INTO LW_TEXT_STR
    SEPARATED BY I_SEPARATOR.
  CONDENSE LW_TEXT_STR.
  E_TEXT = LW_TEXT_STR.





ENDFUNCTION.
