FUNCTION ZFM_ALV_DISPLAY.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_LASTCOL) TYPE  INT4 OPTIONAL
*"     REFERENCE(IT_HEADER) TYPE  ZTT_ALV_HEADER OPTIONAL
*"     REFERENCE(I_LOGO) TYPE  ZST_BM_ALV_LOGO OPTIONAL
*"     REFERENCE(I_CALLBACK_PROGRAM) TYPE  SY-REPID DEFAULT SPACE
*"     REFERENCE(I_CALLBACK_PF_STATUS_SET) TYPE  SLIS_FORMNAME DEFAULT
*"       SPACE
*"     REFERENCE(I_CALLBACK_USER_COMMAND) TYPE  SLIS_FORMNAME DEFAULT
*"       SPACE
*"     REFERENCE(I_CALLBACK_TOP_OF_PAGE) TYPE  SLIS_FORMNAME DEFAULT
*"       SPACE
*"     REFERENCE(I_CALLBACK_HTML_END_OF_LIST) TYPE  SLIS_FORMNAME
*"       DEFAULT SPACE
*"     REFERENCE(I_STRUCTURE_NAME) TYPE  DD02L-TABNAME OPTIONAL
*"     REFERENCE(IT_FIELDCAT) TYPE  LVC_T_FCAT OPTIONAL
*"     REFERENCE(I_GRID_TITLE) TYPE  LVC_TITLE OPTIONAL
*"     REFERENCE(I_GRID_SETTINGS) TYPE  LVC_S_GLAY OPTIONAL
*"     VALUE(IS_LAYOUT_LVC) TYPE  LVC_S_LAYO OPTIONAL
*"     REFERENCE(IT_EXCLUDING) TYPE  UI_FUNCTIONS OPTIONAL
*"     REFERENCE(IT_SPECIAL_GROUPS_LVC) TYPE  LVC_T_SGRP OPTIONAL
*"     REFERENCE(IT_SORT_LVC) TYPE  LVC_T_SORT OPTIONAL
*"     REFERENCE(IT_FILTER_LVC) TYPE  LVC_T_FILT OPTIONAL
*"     REFERENCE(IT_HYPERLINK) TYPE  LVC_T_HYPE OPTIONAL
*"     REFERENCE(IS_SEL_HIDE) TYPE  SLIS_SEL_HIDE_ALV OPTIONAL
*"     REFERENCE(I_DEFAULT) DEFAULT 'X'
*"     VALUE(I_SAVE) DEFAULT 'U'
*"     VALUE(IS_VARIANT) TYPE  DISVARIANT OPTIONAL
*"     REFERENCE(IT_EVENTS) TYPE  SLIS_T_EVENT OPTIONAL
*"     REFERENCE(IT_EVENT_EXIT) TYPE  SLIS_T_EVENT_EXIT OPTIONAL
*"     REFERENCE(IS_PRINT_LVC) TYPE  LVC_S_PRNT OPTIONAL
*"     REFERENCE(IS_REPREP_ID_LVC) TYPE  LVC_S_RPRP OPTIONAL
*"     REFERENCE(I_SCREEN_START_COLUMN) DEFAULT 0
*"     REFERENCE(I_SCREEN_START_LINE) DEFAULT 0
*"     REFERENCE(I_SCREEN_END_COLUMN) DEFAULT 0
*"     REFERENCE(I_SCREEN_END_LINE) DEFAULT 0
*"     REFERENCE(I_HTML_HEIGHT_TOP) TYPE  I OPTIONAL
*"     REFERENCE(I_HTML_HEIGHT_END) TYPE  I OPTIONAL
*"     REFERENCE(IT_ALV_GRAPHICS) TYPE  DTC_T_TC OPTIONAL
*"     REFERENCE(IT_EXCEPT_QINFO_LVC) TYPE  SLIS_T_QINFO_ALV OPTIONAL
*"     REFERENCE(IR_SALV_FULLSCREEN_ADAPTER) TYPE REF TO
*"        CL_SALV_FULLSCREEN_ADAPTER OPTIONAL
*"     REFERENCE(I_BYPASSING_BUFFER) TYPE  XMARK OPTIONAL
*"     REFERENCE(I_SHOW_TOTAL_INFO) TYPE  XMARK OPTIONAL
*"  TABLES
*"      T_OUTTAB
*"----------------------------------------------------------------------
DATA:
    LT_FIELDCAT TYPE LVC_T_FCAT,
    LW_CALLBACK_HTML_TOP_OF_PAGE  TYPE SLIS_FORMNAME,
    LW_CALLBACK_PF_STATUS_SET     TYPE SLIS_FORMNAME,
    LW_CALLBACK_USER_COMMAND      TYPE SLIS_FORMNAME,
    LW_CALLBACK_TOP_OF_PAGE       TYPE SLIS_FORMNAME,
    LW_CALLBACK_HTML_END_OF_LIST  TYPE SLIS_FORMNAME,
    LT_EXCLUDING                  TYPE SLIS_T_EXTAB.
  FIELD-SYMBOLS:
    <LF_FIELDCAT>  TYPE LVC_S_FCAT.

* Init
  CLEAR: LT_FIELDCAT.
  GW_CALLBACK_PROGRAM          = I_CALLBACK_PROGRAM.
  GW_CALLBACK_PF_STATUS_SET    = I_CALLBACK_PF_STATUS_SET.
  GW_CALLBACK_USER_COMMAND     = I_CALLBACK_USER_COMMAND.
  GW_CALLBACK_TOP_OF_PAGE      = I_CALLBACK_TOP_OF_PAGE.
  GW_CALLBACK_HTML_END_OF_LIST = I_CALLBACK_HTML_END_OF_LIST.
  IF I_CALLBACK_PF_STATUS_SET IS NOT INITIAL.
    LW_CALLBACK_PF_STATUS_SET = 'ALV_GRID_PF_STATUS_SET'.
  ENDIF.
  IF I_CALLBACK_USER_COMMAND IS NOT INITIAL.
    LW_CALLBACK_USER_COMMAND = 'ALV_GRID_USER_COMMAND'.
  ENDIF.
  IF I_CALLBACK_TOP_OF_PAGE IS NOT INITIAL
  OR IT_HEADER[] IS NOT INITIAL.
    LW_CALLBACK_HTML_TOP_OF_PAGE = 'ALV_GRID_TOP_HTML'.
    LW_CALLBACK_TOP_OF_PAGE = 'ALV_GRID_TOP_OF_PAGE'.
  ENDIF.
  IF I_CALLBACK_HTML_END_OF_LIST IS NOT INITIAL.
    LW_CALLBACK_HTML_END_OF_LIST = 'ALV_GRID_HTML_END_OF_LIST'.
  ENDIF.

*  BEGIN.

* Create Field catalog
  PERFORM CREATE_FIELDCATALOG
    USING     I_STRUCTURE_NAME
              IT_FIELDCAT[]
              I_LASTCOL
              I_BYPASSING_BUFFER
              SPACE
    CHANGING  LT_FIELDCAT.

* Set disable if need
  PERFORM SET_DISABLE_ALV_ROW
    USING     IS_LAYOUT_LVC
    CHANGING  T_OUTTAB[].

  APPEND LINES OF IT_EXCLUDING TO LT_EXCLUDING.
  PERFORM ALV_SET_VARIANT_LAYOUT
    CHANGING IS_LAYOUT_LVC
             IS_VARIANT
             I_SAVE.

  GT_HEADER[] = IT_HEADER[].
  GS_LOGO     = I_LOGO.

  IF I_SHOW_TOTAL_INFO IS NOT INITIAL.
    ASSIGN T_OUTTAB[] TO <GT_ALV_DATA>.
    PERFORM SHOW_ALV_TOTAL_RECORD USING T_OUTTAB[].
  ENDIF.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY_LVC'
    EXPORTING
      I_CALLBACK_PROGRAM          = 'SAPLZFG_COMMON'
      I_CALLBACK_HTML_TOP_OF_PAGE = LW_CALLBACK_HTML_TOP_OF_PAGE
      I_CALLBACK_PF_STATUS_SET    = LW_CALLBACK_PF_STATUS_SET
      I_CALLBACK_USER_COMMAND     = LW_CALLBACK_USER_COMMAND
      I_CALLBACK_TOP_OF_PAGE      = LW_CALLBACK_TOP_OF_PAGE
      I_CALLBACK_HTML_END_OF_LIST = LW_CALLBACK_HTML_END_OF_LIST
      I_GRID_TITLE                = I_GRID_TITLE
      I_GRID_SETTINGS             = I_GRID_SETTINGS
      IS_LAYOUT_LVC               = IS_LAYOUT_LVC
      IT_FIELDCAT_LVC             = LT_FIELDCAT
      IT_EXCLUDING                = LT_EXCLUDING
      IT_SPECIAL_GROUPS_LVC       = IT_SPECIAL_GROUPS_LVC
      IT_SORT_LVC                 = IT_SORT_LVC
      IT_FILTER_LVC               = IT_FILTER_LVC
      IT_HYPERLINK                = IT_HYPERLINK
      IS_SEL_HIDE                 = IS_SEL_HIDE
      I_DEFAULT                   = I_DEFAULT
      I_SAVE                      = I_SAVE
      IS_VARIANT                  = IS_VARIANT
      IT_EVENTS                   = IT_EVENTS
      IT_EVENT_EXIT               = IT_EVENT_EXIT
      IS_PRINT_LVC                = IS_PRINT_LVC
      IS_REPREP_ID_LVC            = IS_REPREP_ID_LVC
      I_SCREEN_START_COLUMN       = I_SCREEN_START_COLUMN
      I_SCREEN_START_LINE         = I_SCREEN_START_LINE
      I_SCREEN_END_COLUMN         = I_SCREEN_END_COLUMN
      I_SCREEN_END_LINE           = I_SCREEN_END_LINE
      I_HTML_HEIGHT_TOP           = I_HTML_HEIGHT_TOP
      I_HTML_HEIGHT_END           = I_HTML_HEIGHT_END
      IT_ALV_GRAPHICS             = IT_ALV_GRAPHICS
      IT_EXCEPT_QINFO_LVC         = IT_EXCEPT_QINFO_LVC
      IR_SALV_FULLSCREEN_ADAPTER  = IR_SALV_FULLSCREEN_ADAPTER
    TABLES
      T_OUTTAB                    = T_OUTTAB
    EXCEPTIONS
      PROGRAM_ERROR               = 1
      OTHERS                      = 2.





ENDFUNCTION.
