FUNCTION ZFM_FILE_EXCEL_CONVERT_TOTABLE.
*"--------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(I_START_COLUMN) TYPE  I DEFAULT 1
*"  TABLES
*"      T_OUTTAB
*"      T_EXCEL TYPE  SOI_GENERIC_TABLE
*"--------------------------------------------------------------------
DATA:
    LS_EXCEL_DATA   TYPE SOI_GENERIC_ITEM,
    LW_COL          TYPE I,
    LS_EXCEL_NUMBR  TYPE ZST_EXCEL_NUMBR,
    LT_EXCEL_NUMBR  TYPE TABLE OF ZST_EXCEL_NUMBR,
    LS_DATA         TYPE REF TO DATA,
    LS_DIMENS       TYPE SOI_DIMENSION_ITEM.

  FIELD-SYMBOLS:
    <LF_DATA>       TYPE ANY,
    <LF_VALUE>      TYPE ANY.

* Init

*  IF I_TABNAME IS NOT INITIAL.
*    CALL FUNCTION 'REUSE_ALV_FIELDCATALOG_MERGE'
*      EXPORTING
*        I_STRUCTURE_NAME       = I_TABNAME
*      CHANGING
*        CT_FIELDCAT            = LT_FIELDCAT
*      EXCEPTIONS
*        INCONSISTENT_INTERFACE = 1
*        PROGRAM_ERROR          = 2
*        OTHERS                 = 3.
*  ELSE.
*    LT_FIELDCAT[] = T_FIELDCAT[].
*  ENDIF.
*
*  CHECK LT_FIELDCAT[] IS NOT INITIAL.
*
** Sort field category table
*  SORT LT_FIELDCAT BY NO_OUT COL_POS.

* Standard data with data type is number
  LOOP AT T_EXCEL INTO LS_EXCEL_DATA.
    MOVE-CORRESPONDING LS_EXCEL_DATA TO LS_EXCEL_NUMBR.
    APPEND LS_EXCEL_NUMBR TO LT_EXCEL_NUMBR.
  ENDLOOP.
  SORT LT_EXCEL_NUMBR BY ROW COLUMN.

* Get dimension of data square
  CALL FUNCTION 'ZFM_FILE_EXCEL_DATA_GETDIMENS'
    IMPORTING
      E_DIMENSION  = LS_DIMENS
    TABLES
      T_EXCEL_DATA = T_EXCEL.

* Get data
  LOOP AT LT_EXCEL_NUMBR INTO LS_EXCEL_NUMBR.
    AT NEW ROW.
      CREATE DATA LS_DATA LIKE LINE OF T_OUTTAB.
      ASSIGN LS_DATA->* TO <LF_DATA>.
    ENDAT.
    LW_COL = LS_EXCEL_NUMBR-COLUMN - LS_DIMENS-COLUMN + I_START_COLUMN.
    ASSIGN COMPONENT LW_COL OF STRUCTURE <LF_DATA>
      TO <LF_VALUE>.
    MOVE LS_EXCEL_NUMBR-VALUE TO <LF_VALUE>.
    AT END OF ROW.
      APPEND <LF_DATA> TO T_OUTTAB.
    ENDAT.
  ENDLOOP.





ENDFUNCTION.
