*&---------------------------------------------------------------------*
*& Include ZIN_BM_TRAN_TAB_TOP            Report ZPG_BM_TRAN_TAB
*&
*&---------------------------------------------------------------------*

TABLES: TADIR.
TYPES:
  BEGIN OF GTY_OBJECT,
    OBJNAME TYPE TABNAME,
  END OF GTY_OBJECT.

DATA: GT_KEY TYPE APB_LPD_T_E071K,
      GT_OBJ TYPE /SAPCND/T_KO200.
DATA: GW_OBJNAME TYPE TABNAME.

* Parameter for action processing
SELECTION-SCREEN BEGIN OF LINE.
  PARAMETERS:
    P_TRATB  RADIOBUTTON GROUP RG1 DEFAULT 'X' USER-COMMAND TRA.
  SELECTION-SCREEN COMMENT 3(20)  FOR FIELD P_TRATB.
  PARAMETERS:
    P_ALLCS  RADIOBUTTON GROUP RG1.
  SELECTION-SCREEN COMMENT 25(23) FOR FIELD P_ALLCS.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
  PARAMETERS:
    P_TRATR  RADIOBUTTON GROUP RG2 DEFAULT 'X' USER-COMMAND TRA  MODIF ID TCS.
  SELECTION-SCREEN COMMENT 3(20)  FOR FIELD P_TRATR  MODIF ID TCS.
  PARAMETERS:
    P_TRADL  RADIOBUTTON GROUP RG2  MODIF ID TCS.
  SELECTION-SCREEN COMMENT 25(15) FOR FIELD P_TRADL  MODIF ID TCS.
  SELECTION-SCREEN POSITION 45.
  PARAMETERS:
    P_TRAUL  RADIOBUTTON GROUP RG2  MODIF ID TCS.
  SELECTION-SCREEN COMMENT 50(15) FOR FIELD P_TRAUL  MODIF ID TCS.
SELECTION-SCREEN END OF LINE.
SELECT-OPTIONS:
  S_OBJNM FOR GW_OBJNAME MODIF ID TTB,
  S_PACKG FOR TADIR-DEVCLASS MODIF ID TCS.
