*&---------------------------------------------------------------------*
*& Include ZIN_BM_ALVWBTOP                  Report ZPG_BM_ALVWB
*&
*&---------------------------------------------------------------------*

INCLUDE ZIN_COMMONTOP.

**********************************************************************
* CONSTANTS
**********************************************************************
CONSTANTS:
  BEGIN OF C_FCODE ,
    COMP_ADD_CHILD    TYPE UI_FUNC VALUE 'COMP_ADD_CHILD' ,
    COMP_ADD_SIBLING  TYPE UI_FUNC VALUE 'COMP_ADD_SIBLING' ,
    COMP_CLONE        TYPE UI_FUNC VALUE 'COMP_CLONE' ,
    COMP_CLONE_MASS   TYPE UI_FUNC VALUE 'COMP_CLONE_MASS' ,
    COMP_DELETE       TYPE UI_FUNC VALUE 'COMP_DELETE' ,
    COMP_DELETE_MASS  TYPE UI_FUNC VALUE 'COMP_DELETE_MASS' ,
    COMP_SELECTED     TYPE UI_FUNC VALUE 'COMP_SELECTED' ,
    COMP_MOVE_SIBLING_UP   TYPE UI_FUNC VALUE 'COMP_MOVE_SIBLING_UP' ,
    COMP_MOVE_SIBLING_DOWN TYPE UI_FUNC VALUE 'COMP_MOVE_SIBLING_DOWN' ,
    COMP_SELECT_ALL   TYPE UI_FUNC VALUE 'COMP_SELECT_ALL' ,
    COMP_TBSHIFT_MASS TYPE UI_FUNC VALUE 'COMP_TBSHIFT_MASS' ,
    APPL_ACTUALIZE    TYPE UI_FUNC VALUE 'APPL_ACTUALIZE' ,
  END OF C_FCODE,

  BEGIN OF GC_TABLE,
    PROG              TYPE TABNAME VALUE 'ZTB_PROG',
    ALV_LAYOUT        TYPE TABNAME VALUE 'ZTB_BM_ALV_LAYO',
    ALV_FCAT          TYPE TABNAME VALUE 'ZTB_BM_ALV_FCAT',
  END OF GC_TABLE,

  BEGIN OF GC_NODE_LEVEL,
    CONTEXT           TYPE ZDD_ATREE_NODELV VALUE 1,
    SECTION           TYPE ZDD_ATREE_NODELV VALUE 2,
    COMPONENT         TYPE ZDD_ATREE_NODELV VALUE 3,
  END OF GC_NODE_LEVEL,

  BEGIN OF GC_NODE_CODE,
    CONTEXT           TYPE ZDD_ATREE_NODECODE VALUE 'CNTX',
    COMP_HEAD         TYPE ZDD_ATREE_NODECODE VALUE 'HEAD',
    COMP_DETL         TYPE ZDD_ATREE_NODECODE VALUE 'DETL',
  END OF GC_NODE_CODE,

  BEGIN OF GC_NODE_IMG,
    PROGRAM           TYPE TV_IMAGE VALUE '@AL@',
    CONTEXT           TYPE TV_IMAGE VALUE '@LZ@',
    SECT_HEAD         TYPE TV_IMAGE VALUE '@FA@',
    SECT_DETL         TYPE TV_IMAGE VALUE '@FB@',
    COMP_HEAD         TYPE TV_IMAGE VALUE '@HP@',
    COMP_DETL         TYPE TV_IMAGE VALUE '@36@',
    COMPONENT         TYPE TV_IMAGE VALUE '@0Q@',
  END OF GC_NODE_IMG,

  BEGIN OF GC_TREE_KEY,
    CONTEXT           TYPE ZDD_ATREE_AGGRKEY VALUE 'CNTX',
    SECT_HEAD         TYPE ZDD_ATREE_AGGRKEY VALUE 'SECT_1',
    SECT_DETL         TYPE ZDD_ATREE_NODECODE VALUE 'SECT_2',
    COMP_PREF         TYPE ZDD_ATREE_NODECODE VALUE 'COMP_',
  END OF GC_TREE_KEY,

  BEGIN OF GC_CAPTION,
    DUMMY             TYPE SBPTCAPTN-NAME VALUE 'DUMMY',
    CONTEXT           TYPE SBPTCAPTN-NAME VALUE 'ALVSTR',
    COMPONENT         TYPE SBPTCAPTN-NAME VALUE 'COMPONENT',
    FIELDNAME         TYPE SBPTCAPTN-NAME VALUE 'FNAME',
    HEAD_POSID        TYPE SBPTCAPTN-NAME VALUE 'POSID',
    HEAD_TYP          TYPE SBPTCAPTN-NAME VALUE 'TYP',
    HEAD_HKEY         TYPE SBPTCAPTN-NAME VALUE 'HKEY',
    HEAD_PREFIX       TYPE SBPTCAPTN-NAME VALUE 'PREFIX',
    HEAD_SUFFIX       TYPE SBPTCAPTN-NAME VALUE 'SUFFIX',
    DETL_COLS         TYPE SBPTCAPTN-NAME VALUE 'COLS',
    DETL_STYLEFNAME   TYPE SBPTCAPTN-NAME VALUE 'STYLEFNAME',
    DETL_FCAT         TYPE SBPTCAPTN-NAME VALUE 'FIELDCAT',
  END OF GC_CAPTION,
  GC_FCAT_SEPARATOR   TYPE C VALUE ':'.

**********************************************************************
* CLASSES
**********************************************************************
CLASS LCL_WB_HANDLER DEFINITION.
  PUBLIC SECTION.
    METHODS:
      HNDL_TAB_CLICKED
        FOR EVENT CLICKED OF CL_GUI_CONTAINER_BAR_2
          IMPORTING ID  CONTAINER  NAME,
      HNDL_TOOLBAR_FCODE
        FOR EVENT FUNCTION_SELECTED OF CL_GUI_TOOLBAR
          IMPORTING FCODE ,
      HNDL_SELECTION_CHANGED
        FOR EVENT SELECTION_CHANGED OF CL_GUI_ALV_TREE
          IMPORTING NODE_KEY ,
      HNDL_NODE_CONTEXT_MENU_REQ
        FOR EVENT NODE_CONTEXT_MENU_REQUEST OF CL_GUI_ALV_TREE
          IMPORTING NODE_KEY MENU,
      HNDL_NODE_CONTEXT_MENU_SEL
        FOR EVENT NODE_CONTEXT_MENU_SELECTED OF CL_GUI_ALV_TREE
          IMPORTING NODE_KEY FCODE.

ENDCLASS.                    "LCL_WB_HANDLER DEFINITION
**********************************************************************
* DATA
**********************************************************************
DATA:
  GS_PROG                     TYPE ZTB_PROG,
  GT_ALV_LAYO_DB              TYPE TABLE OF ZTB_BM_ALV_LAYO,
  GT_COMP_TREE                TYPE TABLE OF ZST_BM_ALV_LAYO,
  GT_COMP_CONFIG              TYPE LVC_T_FCAT,
  GT_ALV_FCAT_O               TYPE TABLE OF ZTB_BM_ALV_FCAT,
  GT_ALV_FCAT                 TYPE TABLE OF ZTB_BM_ALV_FCAT,
  GO_CON_ROOT                 TYPE REF TO CL_GUI_DOCKING_CONTAINER,
  GO_SPLIT1                   TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
  GO_SPLIT2                   TYPE REF TO CL_GUI_SPLITTER_CONTAINER,
  GO_CON_CONFIG               TYPE REF TO CL_GUI_CONTAINER,
  GO_CON_TEMPLATE             TYPE REF TO CL_GUI_CONTAINER,
  GO_CON_COMPONENT            TYPE REF TO CL_GUI_CONTAINER,
  GO_CON_COMCONFIG            TYPE REF TO CL_GUI_CONTAINER,
  GO_CON_BAR                  TYPE REF TO CL_GUI_CONTAINER_BAR_2,
  GT_CAPTIONS                 TYPE SBPTCAPTNS,
  GO_ALV_GRID                 TYPE REF TO CL_GUI_ALV_GRID,
  GO_ALV_HEADER_DOC           TYPE REF TO CL_DD_DOCUMENT,
  GO_COMPTREE                 TYPE REF TO CL_GUI_ALV_TREE,
  GO_WB_HANDLER               TYPE REF TO LCL_WB_HANDLER.
*  GO_PROTAB                   TYPE REF TO LCL_WB_PROTAB,
*  GO_FORMTEMPLATE             TYPE REF TO LCL_FORMTEMPLATE .
FIELD-SYMBOLS:
  <GF_CONTEXT>                TYPE ANY,
  <GFT_ALV_DATA>              TYPE TABLE.

**********************************************************************
* PARAMETERS AND SELECT-OPTIONS
**********************************************************************
PARAMETERS:
  P_REPORT                    TYPE ZTB_BM_ALV_LAYO-REPORT
                                DEFAULT 'ZPG_IRET_RP_RUN'.
